<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>clinical_trial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="10.1_clinical_trial_files/libs/clipboard/clipboard.min.js"></script>
<script src="10.1_clinical_trial_files/libs/quarto-html/quarto.js"></script>
<script src="10.1_clinical_trial_files/libs/quarto-html/popper.min.js"></script>
<script src="10.1_clinical_trial_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="10.1_clinical_trial_files/libs/quarto-html/anchor.min.js"></script>
<link href="10.1_clinical_trial_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="10.1_clinical_trial_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="10.1_clinical_trial_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="10.1_clinical_trial_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="10.1_clinical_trial_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#clinical-trial-hipponol-intervention-study" id="toc-clinical-trial-hipponol-intervention-study" class="nav-link active" data-scroll-target="#clinical-trial-hipponol-intervention-study">🧪 Clinical Trial: Hipponol Intervention Study</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a>
  <ul class="collapse">
  <li><a href="#study-design" id="toc-study-design" class="nav-link" data-scroll-target="#study-design">Study Design</a></li>
  <li><a href="#analysis-plan" id="toc-analysis-plan" class="nav-link" data-scroll-target="#analysis-plan">Analysis Plan</a>
  <ul class="collapse">
  <li><a href="#descriptive-analysis-baseline" id="toc-descriptive-analysis-baseline" class="nav-link" data-scroll-target="#descriptive-analysis-baseline">🔍 Descriptive Analysis (Baseline)</a></li>
  <li><a href="#outcome-analysis" id="toc-outcome-analysis" class="nav-link" data-scroll-target="#outcome-analysis">📉 Outcome Analysis</a></li>
  <li><a href="#primary-endpoint" id="toc-primary-endpoint" class="nav-link" data-scroll-target="#primary-endpoint">Primary endpoint</a></li>
  <li><a href="#notes" id="toc-notes" class="nav-link" data-scroll-target="#notes">📌 Notes</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#step-1-setting-up-python-for-the-hipponol-trial" id="toc-step-1-setting-up-python-for-the-hipponol-trial" class="nav-link" data-scroll-target="#step-1-setting-up-python-for-the-hipponol-trial">🛠️ Step 1: Setting Up Python for the Hipponol Trial</a>
  <ul class="collapse">
  <li><a href="#requirements" id="toc-requirements" class="nav-link" data-scroll-target="#requirements">✅ Requirements</a></li>
  </ul></li>
  <li><a href="#baseline-comparison-table-1" id="toc-baseline-comparison-table-1" class="nav-link" data-scroll-target="#baseline-comparison-table-1">📊 Baseline Comparison: Table 1</a>
  <ul class="collapse">
  <li><a href="#table-1-summary-function" id="toc-table-1-summary-function" class="nav-link" data-scroll-target="#table-1-summary-function">🔍 Table 1: Summary Function</a></li>
  <li><a href="#exploring-distributions" id="toc-exploring-distributions" class="nav-link" data-scroll-target="#exploring-distributions">📊 Exploring Distributions</a>
  <ul class="collapse">
  <li><a href="#focus-baseline-blood-pressure-and-age" id="toc-focus-baseline-blood-pressure-and-age" class="nav-link" data-scroll-target="#focus-baseline-blood-pressure-and-age">🎯 Focus: Baseline Blood Pressure and Age</a></li>
  </ul></li>
  <li><a href="#visualising-distributions" id="toc-visualising-distributions" class="nav-link" data-scroll-target="#visualising-distributions">🔍 Visualising Distributions</a>
  <ul class="collapse">
  <li><a href="#interpretation-tips" id="toc-interpretation-tips" class="nav-link" data-scroll-target="#interpretation-tips">💡 Interpretation Tips</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#primary-endpoint-1" id="toc-primary-endpoint-1" class="nav-link" data-scroll-target="#primary-endpoint-1">Primary endpoint</a>
  <ul class="collapse">
  <li><a href="#analysing-survival-outcomes" id="toc-analysing-survival-outcomes" class="nav-link" data-scroll-target="#analysing-survival-outcomes">🧬 Analysing Survival Outcomes</a>
  <ul class="collapse">
  <li><a href="#quick-check-chi-squared-test-for-survival" id="toc-quick-check-chi-squared-test-for-survival" class="nav-link" data-scroll-target="#quick-check-chi-squared-test-for-survival">🧪 Quick Check: Chi-squared Test for Survival</a></li>
  </ul></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression">🔎 Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#what-is-logistic-regression" id="toc-what-is-logistic-regression" class="nav-link" data-scroll-target="#what-is-logistic-regression">💡 What is logistic regression?</a></li>
  <li><a href="#example-interpretation" id="toc-example-interpretation" class="nav-link" data-scroll-target="#example-interpretation">📌 Example Interpretation</a></li>
  <li><a href="#optional-add-other-variables" id="toc-optional-add-other-variables" class="nav-link" data-scroll-target="#optional-add-other-variables">📎 Optional: Add other variables</a></li>
  <li><a href="#confidence-intervals-for-odds-ratios" id="toc-confidence-intervals-for-odds-ratios" class="nav-link" data-scroll-target="#confidence-intervals-for-odds-ratios">📏 Confidence Intervals for Odds Ratios</a></li>
  <li><a href="#how-to-interpret-this" id="toc-how-to-interpret-this" class="nav-link" data-scroll-target="#how-to-interpret-this">🧠 How to interpret this:</a></li>
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">📌 Example:</a></li>
  </ul></li>
  <li><a href="#bayesian-logistic-regression-survival" id="toc-bayesian-logistic-regression-survival" class="nav-link" data-scroll-target="#bayesian-logistic-regression-survival">Bayesian Logistic Regression – Survival</a>
  <ul class="collapse">
  <li><a href="#why-bayesian" id="toc-why-bayesian" class="nav-link" data-scroll-target="#why-bayesian">🧮 Why Bayesian?</a></li>
  <li><a href="#goal" id="toc-goal" class="nav-link" data-scroll-target="#goal">🎯 Goal</a></li>
  <li><a href="#define-predictor-and-outcome" id="toc-define-predictor-and-outcome" class="nav-link" data-scroll-target="#define-predictor-and-outcome">📦 Define Predictor and Outcome</a></li>
  </ul></li>
  <li><a href="#step-by-step-bayesian-logistic-regression-in-pymc" id="toc-step-by-step-bayesian-logistic-regression-in-pymc" class="nav-link" data-scroll-target="#step-by-step-bayesian-logistic-regression-in-pymc">🔧 Step-by-Step: Bayesian Logistic Regression in PyMC</a>
  <ul class="collapse">
  <li><a href="#model-structure" id="toc-model-structure" class="nav-link" data-scroll-target="#model-structure">📐 Model Structure</a></li>
  <li><a href="#pymc-model-code" id="toc-pymc-model-code" class="nav-link" data-scroll-target="#pymc-model-code">📦 PyMC Model Code</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">🧠 Interpretation</a></li>
  </ul></li>
  <li><a href="#kaplanmeier-survival-curves" id="toc-kaplanmeier-survival-curves" class="nav-link" data-scroll-target="#kaplanmeier-survival-curves">📈 Kaplan–Meier Survival Curves</a>
  <ul class="collapse">
  <li><a href="#why-kaplanmeier" id="toc-why-kaplanmeier" class="nav-link" data-scroll-target="#why-kaplanmeier">🔍 Why Kaplan–Meier?</a></li>
  <li><a href="#interpretation-1" id="toc-interpretation-1" class="nav-link" data-scroll-target="#interpretation-1">📘 Interpretation</a></li>
  </ul></li>
  <li><a href="#compare-groups-statistically-log-rank-test" id="toc-compare-groups-statistically-log-rank-test" class="nav-link" data-scroll-target="#compare-groups-statistically-log-rank-test">🧪 Compare groups statistically – Log-rank test</a>
  <ul class="collapse">
  <li><a href="#what-is-the-log-rank-test" id="toc-what-is-the-log-rank-test" class="nav-link" data-scroll-target="#what-is-the-log-rank-test">🔍 What is the Log-Rank Test?</a></li>
  <li><a href="#when-to-use" id="toc-when-to-use" class="nav-link" data-scroll-target="#when-to-use">🧪 When to Use:</a></li>
  </ul></li>
  <li><a href="#cox-proportional-hazards-model-a-detailed-guide" id="toc-cox-proportional-hazards-model-a-detailed-guide" class="nav-link" data-scroll-target="#cox-proportional-hazards-model-a-detailed-guide">Cox Proportional Hazards Model: A Detailed Guide</a>
  <ul class="collapse">
  <li><a href="#what-is-the-cox-proportional-hazards-model" id="toc-what-is-the-cox-proportional-hazards-model" class="nav-link" data-scroll-target="#what-is-the-cox-proportional-hazards-model">✅ What Is the Cox Proportional Hazards Model?</a></li>
  <li><a href="#core-idea" id="toc-core-idea" class="nav-link" data-scroll-target="#core-idea">Core idea:</a></li>
  </ul></li>
  <li><a href="#how-to-fit-it-in-python-with-lifelines" id="toc-how-to-fit-it-in-python-with-lifelines" class="nav-link" data-scroll-target="#how-to-fit-it-in-python-with-lifelines">🛠️ 2. How to Fit It in Python (with <code>lifelines</code>)</a>
  <ul class="collapse">
  <li><a href="#how-to-interpret-the-output" id="toc-how-to-interpret-the-output" class="nav-link" data-scroll-target="#how-to-interpret-the-output">📏 How to Interpret the Output</a></li>
  <li><a href="#example-interpretation-1" id="toc-example-interpretation-1" class="nav-link" data-scroll-target="#example-interpretation-1">Example Interpretation:</a></li>
  <li><a href="#test-the-proportional-hazards-ph-assumption" id="toc-test-the-proportional-hazards-ph-assumption" class="nav-link" data-scroll-target="#test-the-proportional-hazards-ph-assumption">⚠️ Test the Proportional Hazards (PH) Assumption</a></li>
  <li><a href="#if-ph-is-violated" id="toc-if-ph-is-violated" class="nav-link" data-scroll-target="#if-ph-is-violated">If PH is violated:</a></li>
  <li><a href="#optional-predict-or-visualise" id="toc-optional-predict-or-visualise" class="nav-link" data-scroll-target="#optional-predict-or-visualise">🧪 5. (Optional) Predict or Visualise</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#secondary-endpoint-blood-pressure-change" id="toc-secondary-endpoint-blood-pressure-change" class="nav-link" data-scroll-target="#secondary-endpoint-blood-pressure-change">🧪 Secondary Endpoint: Blood Pressure Change</a>
  <ul class="collapse">
  <li><a href="#visual-exploration-of-distributions" id="toc-visual-exploration-of-distributions" class="nav-link" data-scroll-target="#visual-exploration-of-distributions">1. 🎨 Visual Exploration of Distributions</a>
  <ul class="collapse">
  <li><a href="#baseline" id="toc-baseline" class="nav-link" data-scroll-target="#baseline">Baseline</a></li>
  <li><a href="#follow-up" id="toc-follow-up" class="nav-link" data-scroll-target="#follow-up">Follow-up</a></li>
  <li><a href="#change-in-blood-pressure" id="toc-change-in-blood-pressure" class="nav-link" data-scroll-target="#change-in-blood-pressure">Change in Blood Pressure</a></li>
  </ul></li>
  <li><a href="#t-test-for-comparing-change-in-sbp-between-two-groups" id="toc-t-test-for-comparing-change-in-sbp-between-two-groups" class="nav-link" data-scroll-target="#t-test-for-comparing-change-in-sbp-between-two-groups">🔍 t-Test for Comparing Change in SBP Between Two Groups</a>
  <ul class="collapse">
  <li><a href="#what-is-it" id="toc-what-is-it" class="nav-link" data-scroll-target="#what-is-it">What is it?</a></li>
  <li><a href="#when-to-use-it" id="toc-when-to-use-it" class="nav-link" data-scroll-target="#when-to-use-it">🧪 When to use it</a></li>
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses">🧠 Hypotheses</a></li>
  </ul></li>
  <li><a href="#interpreting-results" id="toc-interpreting-results" class="nav-link" data-scroll-target="#interpreting-results">🧾 Interpreting results</a></li>
  <li><a href="#anova-and-ancova" id="toc-anova-and-ancova" class="nav-link" data-scroll-target="#anova-and-ancova">🧪 ANOVA and ANCOVA</a>
  <ul class="collapse">
  <li><a href="#analysis-of-variance-anova" id="toc-analysis-of-variance-anova" class="nav-link" data-scroll-target="#analysis-of-variance-anova">Analysis of Variance (ANOVA)</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">🔍 Assumptions:</a></li>
  <li><a href="#comparison-t-test-vs.-anova" id="toc-comparison-t-test-vs.-anova" class="nav-link" data-scroll-target="#comparison-t-test-vs.-anova">🧪 Comparison: t-test vs.&nbsp;ANOVA</a></li>
  </ul></li>
  <li><a href="#mathematical-note" id="toc-mathematical-note" class="nav-link" data-scroll-target="#mathematical-note">📐 Mathematical Note</a></li>
  <li><a href="#when-to-use-each" id="toc-when-to-use-each" class="nav-link" data-scroll-target="#when-to-use-each">✅ When to Use Each?</a></li>
  <li><a href="#practical-implication" id="toc-practical-implication" class="nav-link" data-scroll-target="#practical-implication">🔄 Practical Implication</a>
  <ul class="collapse">
  <li><a href="#analysis-of-covariance-ancova" id="toc-analysis-of-covariance-ancova" class="nav-link" data-scroll-target="#analysis-of-covariance-ancova">Analysis of Covariance (ANCOVA)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#regression-analysis-blood-pressure-change" id="toc-regression-analysis-blood-pressure-change" class="nav-link" data-scroll-target="#regression-analysis-blood-pressure-change">Regression Analysis: Blood Pressure Change</a>
  <ul class="collapse">
  <li><a href="#step-4-regression-with-covariates-optional" id="toc-step-4-regression-with-covariates-optional" class="nav-link" data-scroll-target="#step-4-regression-with-covariates-optional">🧮 Step 4: Regression with Covariates (Optional)</a>
  <ul class="collapse">
  <li><a href="#interpretation-2" id="toc-interpretation-2" class="nav-link" data-scroll-target="#interpretation-2">🧠 Interpretation</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#bayesian-regression-analysis-sbp-change" id="toc-bayesian-regression-analysis-sbp-change" class="nav-link" data-scroll-target="#bayesian-regression-analysis-sbp-change">🧠 Bayesian Regression Analysis (SBP Change)</a></li>
  <li><a href="#interpretation-3" id="toc-interpretation-3" class="nav-link" data-scroll-target="#interpretation-3">Interpretation</a></li>
  <li><a href="#comparing-treatment-effects-on-sbp-change" id="toc-comparing-treatment-effects-on-sbp-change" class="nav-link" data-scroll-target="#comparing-treatment-effects-on-sbp-change">🧪 Comparing Treatment Effects on SBP Change</a>
  <ul class="collapse">
  <li><a href="#t-test" id="toc-t-test" class="nav-link" data-scroll-target="#t-test">🔹 T-test</a></li>
  <li><a href="#ancova" id="toc-ancova" class="nav-link" data-scroll-target="#ancova">🔹 ANCOVA</a></li>
  <li><a href="#ols-regression" id="toc-ols-regression" class="nav-link" data-scroll-target="#ols-regression">🔹 OLS Regression</a></li>
  <li><a href="#bayesian-regression" id="toc-bayesian-regression" class="nav-link" data-scroll-target="#bayesian-regression">🔹 Bayesian Regression</a>
  <ul class="collapse">
  <li><a href="#relationship-between-ancova-and-ols-regression" id="toc-relationship-between-ancova-and-ols-regression" class="nav-link" data-scroll-target="#relationship-between-ancova-and-ols-regression">🔄 Relationship Between ANCOVA and OLS Regression</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#summary-of-key-findings" id="toc-summary-of-key-findings" class="nav-link" data-scroll-target="#summary-of-key-findings">📜 Summary of Key Findings</a>
  <ul class="collapse">
  <li><a href="#primary-outcome-survival" id="toc-primary-outcome-survival" class="nav-link" data-scroll-target="#primary-outcome-survival">🧬 Primary Outcome: Survival</a></li>
  <li><a href="#secondary-outcome-systolic-blood-pressure-sbp" id="toc-secondary-outcome-systolic-blood-pressure-sbp" class="nav-link" data-scroll-target="#secondary-outcome-systolic-blood-pressure-sbp">💉 Secondary Outcome: Systolic Blood Pressure (SBP)</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">




<section id="clinical-trial-hipponol-intervention-study" class="level1">
<h1>🧪 Clinical Trial: Hipponol Intervention Study</h1>
<p>This notebook explores data from a simulated 2-year clinical trial testing the effects of a novel nutrient, <strong>Hipponol</strong>, on blood pressure and survival.</p>
</section>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<section id="study-design" class="level2">
<h2 class="anchored" data-anchor-id="study-design">Study Design</h2>
<ul>
<li><strong>Population</strong>: 1000 participants, aged 40–70, male/female, smokers and non-smokers.</li>
<li><strong>Design</strong>: Randomised controlled trial (RCT), 1:1 allocation to Hipponol vs.&nbsp;placebo.</li>
<li><strong>Blinding</strong>: Double-blind.</li>
<li><strong>Duration</strong>: 2-year follow-up.</li>
<li><strong>Outcomes</strong>:
<ul>
<li><strong>Primary</strong>: Survival at 2 years.</li>
<li><strong>Secondary</strong>: Change in systolic blood pressure (SBP) from baseline to follow-up.</li>
</ul></li>
</ul>
</section>
<section id="analysis-plan" class="level2">
<h2 class="anchored" data-anchor-id="analysis-plan">Analysis Plan</h2>
<p>This notebook will follow key elements of the <strong>CONSORT guidelines</strong> for RCT reporting.</p>
<section id="descriptive-analysis-baseline" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-analysis-baseline">🔍 Descriptive Analysis (Baseline)</h3>
<ul>
<li>Generate a <strong>Table 1</strong> comparing baseline characteristics (age, sex, smoking status, baseline SBP) between groups.</li>
<li>Use appropriate statistical tests:
<ul>
<li>Continuous variables: t-test or Mann–Whitney U</li>
<li>Categorical variables: Chi-squared test</li>
</ul></li>
</ul>
</section>
<section id="outcome-analysis" class="level3">
<h3 class="anchored" data-anchor-id="outcome-analysis">📉 Outcome Analysis</h3>
<p>Analysis of results using <strong>Bayesian</strong> and <strong>Frequentist</strong> methods</p>
</section>
<section id="primary-endpoint" class="level3">
<h3 class="anchored" data-anchor-id="primary-endpoint">Primary endpoint</h3>
<ul>
<li><strong>Survival</strong>:
<ul>
<li>Logistic regression</li>
<li>Kaplan–Meier survival curves by group.</li>
<li>Log-rank test and Cox proportional hazards model.</li>
</ul></li>
<li><strong>Blood Pressure</strong>:
<ul>
<li>Compare change in SBP using paired and unpaired t-tests.</li>
<li>Adjust for baseline covariates using linear regression.</li>
</ul></li>
</ul>
</section>
<section id="notes" class="level3">
<h3 class="anchored" data-anchor-id="notes">📌 Notes</h3>
<ul>
<li>Missing data handling: listwise deletion for simplicity.</li>
<li>Sensitivity analyses optional (not shown in basic notebook).</li>
<li>Assumptions for all statistical models will be checked.</li>
</ul>
<details>
<summary>
🦛 Fun Fact
</summary>
The nutrient Hipponol is purely fictional—but if hippos had trials, we bet they’d run them by CONSORT too!
</details>
<div id="2ad31eff" class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Setup for Google Colab: Fetch datasets automatically or manually</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> google.colab <span class="im">import</span> files</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the module and dataset for this notebook</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>MODULE <span class="op">=</span> <span class="st">'10_mini_projects'</span>  </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>DATASET <span class="op">=</span> <span class="st">'hipponol_trial_data.csv'</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>BASE_PATH <span class="op">=</span> <span class="st">'/content/data-analysis-toolkit-FNS'</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>MODULE_PATH <span class="op">=</span> os.path.join(BASE_PATH, <span class="st">'notebooks'</span>, MODULE)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>DATASET_PATH <span class="op">=</span> os.path.join(<span class="st">'data'</span>, DATASET)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Attempt to clone the repository (automatic method)</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Note: If you encounter a cloning error (e.g., 'fatal: destination path already exists'),</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">#       reset the runtime (Runtime &gt; Restart runtime) and run this cell again.</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Attempting to clone repository...'</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> os.path.exists(BASE_PATH):</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">'Repository already exists, skipping clone.'</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>        <span class="op">!</span>git clone https:<span class="op">//</span>github.com<span class="op">/</span>ggkuhnle<span class="op">/</span>data<span class="op">-</span>analysis<span class="op">-</span>toolkit<span class="op">-</span>FNS.git</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Debug: Print directory structure</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Listing repository contents:'</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    <span class="op">!</span>ls {BASE_PATH}</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Listing notebooks directory contents:'</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="op">!</span>ls {BASE_PATH}<span class="op">/</span>notebooks</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Check if the module directory exists</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> os.path.exists(MODULE_PATH):</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">FileNotFoundError</span>(<span class="ss">f'Module directory </span><span class="sc">{</span>MODULE_PATH<span class="sc">}</span><span class="ss"> not found. Check the repository structure.'</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Set working directory to the notebook's folder</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    os.chdir(MODULE_PATH)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Verify dataset is accessible</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> os.path.exists(DATASET_PATH):</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'Dataset found: </span><span class="sc">{</span>DATASET_PATH<span class="sc">}</span><span class="ss"> 🦛'</span>)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'Error: Dataset </span><span class="sc">{</span>DATASET<span class="sc">}</span><span class="ss"> not found after cloning.'</span>)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">FileNotFoundError</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Cloning failed: </span><span class="sc">{</span>e<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Falling back to manual upload option...'</span>)</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Step 2: Manual upload option</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Please upload </span><span class="sc">{</span>DATASET<span class="sc">}</span><span class="ss"> manually.'</span>)</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'1. Click the "Choose Files" button below.'</span>)</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'2. Select </span><span class="sc">{</span>DATASET<span class="sc">}</span><span class="ss"> from your local machine.'</span>)</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'3. Ensure the file is placed in notebooks/</span><span class="sc">{</span>MODULE<span class="sc">}</span><span class="ss">/data/'</span>)</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create the data directory if it doesn't exist</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>    os.makedirs(<span class="st">'data'</span>, exist_ok<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Prompt user to upload the dataset</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>    uploaded <span class="op">=</span> files.upload()</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Check if the dataset was uploaded</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> DATASET <span class="kw">in</span> uploaded:</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>        <span class="cf">with</span> <span class="bu">open</span>(DATASET_PATH, <span class="st">'wb'</span>) <span class="im">as</span> f:</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>            f.write(uploaded[DATASET])</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'Successfully uploaded </span><span class="sc">{</span>DATASET<span class="sc">}</span><span class="ss"> to </span><span class="sc">{</span>DATASET_PATH<span class="sc">}</span><span class="ss"> 🦛'</span>)</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">FileNotFoundError</span>(<span class="ss">f'Upload failed. Please ensure you uploaded </span><span class="sc">{</span>DATASET<span class="sc">}</span><span class="ss">.'</span>)</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="co"># Install required packages for this notebook</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>pip install pandas numpy</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>pip install lifelines</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>pip install pymc</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>pip install arviz</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Python environment ready.'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="step-1-setting-up-python-for-the-hipponol-trial" class="level1">
<h1>🛠️ Step 1: Setting Up Python for the Hipponol Trial</h1>
<p>This section ensures you’re ready to run the analyses in Google Colab or a local environment.</p>
<section id="requirements" class="level2">
<h2 class="anchored" data-anchor-id="requirements">✅ Requirements</h2>
<ul>
<li><p><a href="https://pandas.pydata.org/"><strong>pandas</strong></a>: Used for handling and manipulating tabular data (DataFrames).<br>
<em>We use pandas to structure and prepare the clinical trial data for analysis.</em></p></li>
<li><p><a href="https://numpy.org/"><strong>numpy</strong></a>: Provides efficient numerical operations, including array handling and random number generation.<br>
<em>We use numpy for data generation, numerical summaries, and efficient computation.</em></p></li>
<li><p><a href="https://matplotlib.org/"><strong>matplotlib</strong></a>: Generates static plots and visualisations (e.g., line plots, histograms, and KDEs).<br>
<em>We use matplotlib to create figures illustrating key findings and trends.</em></p></li>
<li><p><a href="https://scipy.org/"><strong>scipy</strong></a>: Offers statistical functions and tests (e.g., t-tests, chi-squared tests).<br>
<em>We use scipy for hypothesis testing and basic statistical analysis.</em></p></li>
<li><p><a href="https://lifelines.readthedocs.io/"><strong>lifelines</strong></a>: Supports survival analysis, including Kaplan–Meier estimation and Cox proportional hazards models.<br>
<em>We use lifelines to model and visualise survival outcomes over the intervention period.</em></p></li>
<li><p><a href="https://seaborn.pydata.org/"><strong>seaborn</strong></a>: Enhances data visualisation, providing high-level functions for attractive statistical plots (e.g., KDE plots).<br>
<em>We use seaborn to simplify and beautify plots, especially distributions and correlations.</em></p></li>
<li><p><a href="https://www.pymc.io/"><strong>pymc</strong></a>: Enables building and sampling from Bayesian statistical models.<br>
<em>We use pymc to fit Bayesian models for endpoints such as survival and blood pressure change.</em></p></li>
<li><p><a href="https://www.arviz.org/"><strong>arviz</strong></a>: Summarises, visualises, and diagnoses outputs from Bayesian models.<br>
<em>We use arviz to assess model fit and interpret posterior distributions.</em></p></li>
</ul>
<div id="c3195c8b" class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Setup</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Import libraries for data manipulation, visualisation, and statistical analysis</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd            <span class="co"># For data manipulation and analysis</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np             <span class="co"># For numerical operations</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt <span class="co"># For plotting</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns          <span class="co"># For enhanced statistical visualisations</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind, chi2_contingency  <span class="co"># For hypothesis testing</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Import Bayesian modelling and visualisation libraries</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pymc <span class="im">as</span> pm              <span class="co"># For Bayesian statistical modelling</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> arviz <span class="im">as</span> az             <span class="co"># For Bayesian inference visualisation</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> lifelines <span class="im">import</span> KaplanMeierFitter</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> lifelines <span class="im">import</span> CoxPHFitter</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> patsy</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="baseline-comparison-table-1" class="level1">
<h1>📊 Baseline Comparison: Table 1</h1>
<p>This section generates a <strong>Table 1</strong> summary of participant characteristics by study group (Hipponol vs Control), including:</p>
<ul>
<li>Means and standard deviations for continuous variables<br>
</li>
<li>Frequencies and percentages for categorical variables<br>
</li>
<li>Statistical comparison (t-test or chi-squared)</li>
</ul>
<div id="b2ac8873" class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the dataset (adjust path as needed)</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"data/hipponol_trial_data.csv"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a copy to avoid modifying original</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>df1 <span class="op">=</span> df.copy()</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Display first few rows</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>df1.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="table-1-summary-function" class="level2">
<h2 class="anchored" data-anchor-id="table-1-summary-function">🔍 Table 1: Summary Function</h2>
<p>This cell builds a summary table comparing baseline characteristics across treatment groups using <strong>standard Python libraries</strong>:</p>
<ul>
<li><strong>Numerical variables</strong> (e.g., age, baseline BP) are compared using independent t-tests. We report mean ± standard deviation.</li>
<li><strong>Categorical variables</strong> (e.g., gender, smoker) are compared using chi-squared tests, and shown as counts with percentages.</li>
</ul>
<p>The function <code>create_table1()</code>:</p>
<ul>
<li>Takes the dataset and grouping column (e.g., “<code>group</code>”) as input.</li>
<li>Returns a DataFrame summarising each variable by group, along with p-values for between-group comparisons.</li>
</ul>
<p>This approach is useful when you want:</p>
<ul>
<li>Full control over what’s included in the table.</li>
<li>Clear, interpretable formatting for reports or publications.</li>
</ul>
<p>To avoid installing additional packages (e.g., tableone).</p>
<p>🛠️ This method aligns with <strong>CONSORT guidelines</strong> for reporting baseline characteristics.</p>
<div id="a8799368" class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> create_table1_clean(data, group_col):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Create a clean Table 1: baseline characteristics by group."""</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> group_col <span class="kw">not</span> <span class="kw">in</span> data.columns:</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">KeyError</span>(<span class="ss">f"Grouping column '</span><span class="sc">{</span>group_col<span class="sc">}</span><span class="ss">' not found in DataFrame."</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    group_names <span class="op">=</span> data[group_col].unique()</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(group_names) <span class="op">!=</span> <span class="dv">2</span>:</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"This function currently supports exactly two groups."</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    group1, group2 <span class="op">=</span> group_names</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    summary <span class="op">=</span> []</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    numeric_cols <span class="op">=</span> [<span class="st">'Age'</span>, <span class="st">'Baseline_SBP'</span>]</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    cat_cols <span class="op">=</span> [<span class="st">'Sex'</span>, <span class="st">'SmokingStatus'</span>]</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Continuous variables</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> numeric_cols:</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>        vals1 <span class="op">=</span> data[data[group_col] <span class="op">==</span> group1][col].dropna()</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>        vals2 <span class="op">=</span> data[data[group_col] <span class="op">==</span> group2][col].dropna()</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>        mean1, std1 <span class="op">=</span> vals1.mean(), vals1.std()</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>        mean2, std2 <span class="op">=</span> vals2.mean(), vals2.std()</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>        t_stat, p_val <span class="op">=</span> ttest_ind(vals1, vals2)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>        summary.append({</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>            <span class="st">'Variable'</span>: col,</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f'</span><span class="sc">{</span>group1<span class="sc">}</span><span class="ss"> (Mean ± SD)'</span>: <span class="ss">f'</span><span class="sc">{</span>mean1<span class="sc">:.1f}</span><span class="ss"> ± </span><span class="sc">{</span>std1<span class="sc">:.1f}</span><span class="ss">'</span>,</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f'</span><span class="sc">{</span>group2<span class="sc">}</span><span class="ss"> (Mean ± SD)'</span>: <span class="ss">f'</span><span class="sc">{</span>mean2<span class="sc">:.1f}</span><span class="ss"> ± </span><span class="sc">{</span>std2<span class="sc">:.1f}</span><span class="ss">'</span>,</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>            <span class="st">'p-value'</span>: <span class="ss">f'</span><span class="sc">{</span>p_val<span class="sc">:.3f}</span><span class="ss">'</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>        })</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Categorical variables</span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> cat_cols:</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>        cont_table <span class="op">=</span> pd.crosstab(data[col], data[group_col])</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>        chi2, p_val, _, _ <span class="op">=</span> chi2_contingency(cont_table)</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i, cat <span class="kw">in</span> <span class="bu">enumerate</span>(cont_table.index):</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>            row <span class="op">=</span> {</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>                <span class="st">'Variable'</span>: <span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss"> = </span><span class="sc">{</span>cat<span class="sc">}</span><span class="ss">"</span>,</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>                <span class="ss">f'</span><span class="sc">{</span>group1<span class="sc">}</span><span class="ss"> (Count %)'</span>: <span class="ss">f"</span><span class="sc">{</span>cont_table<span class="sc">.</span>loc[cat, group1]<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span>cont_table<span class="sc">.</span>loc[cat, group1] <span class="op">/</span> cont_table[group1]<span class="sc">.</span><span class="bu">sum</span>() <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%)"</span>,</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>                <span class="ss">f'</span><span class="sc">{</span>group2<span class="sc">}</span><span class="ss"> (Count %)'</span>: <span class="ss">f"</span><span class="sc">{</span>cont_table<span class="sc">.</span>loc[cat, group2]<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span>cont_table<span class="sc">.</span>loc[cat, group2] <span class="op">/</span> cont_table[group2]<span class="sc">.</span><span class="bu">sum</span>() <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%)"</span>,</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>                <span class="st">'p-value'</span>: <span class="ss">f"</span><span class="sc">{</span>p_val<span class="sc">:.3f}</span><span class="ss">"</span> <span class="cf">if</span> i <span class="op">==</span> <span class="dv">0</span> <span class="cf">else</span> <span class="st">''</span></span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>            }</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>            summary.append(row)</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.DataFrame(summary)</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a><span class="co"># Create and show Table 1</span></span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a>table1_df <span class="op">=</span> create_table1_clean(df1, group_col<span class="op">=</span><span class="st">'Group'</span>)</span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a>display(table1_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exploring-distributions" class="level2">
<h2 class="anchored" data-anchor-id="exploring-distributions">📊 Exploring Distributions</h2>
<p>Before diving into inferential statistics, it’s crucial to understand the <strong>distribution</strong> of our variables. This helps us:</p>
<ul>
<li>Check whether groups are comparable</li>
<li>Identify outliers or skewed data</li>
<li>Decide which statistical tests are appropriate (e.g., parametric vs.&nbsp;non-parametric)</li>
</ul>
<section id="focus-baseline-blood-pressure-and-age" class="level3">
<h3 class="anchored" data-anchor-id="focus-baseline-blood-pressure-and-age">🎯 Focus: Baseline Blood Pressure and Age</h3>
<p>For this study, we’ll explore:</p>
<ul>
<li><strong>Age</strong></li>
<li><strong>Baseline Systolic Blood Pressure (SBP)</strong></li>
</ul>
<p>These continuous variables should ideally be similarly distributed across the control and intervention groups if randomisation was successful.</p>
<hr>
</section>
</section>
<section id="visualising-distributions" class="level2">
<h2 class="anchored" data-anchor-id="visualising-distributions">🔍 Visualising Distributions</h2>
<p>We can use the following plots to explore the distribution:</p>
<ul>
<li><strong>Histogram</strong>: Shows the shape of the distribution (e.g.&nbsp;normal, skewed)</li>
<li><strong>Boxplot</strong>: Useful for comparing groups and spotting outliers</li>
<li><strong>Violin plot (<em>optional</em>)</strong>: Combines boxplot with a kernel density estimate</li>
</ul>
<div id="5b5de39e" class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Set plotting style</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>(style<span class="op">=</span><span class="st">"whitegrid"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot: Distribution of Age</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">4</span>))</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>df1, x<span class="op">=</span><span class="st">'Age'</span>, hue<span class="op">=</span><span class="st">'Group'</span>, kde<span class="op">=</span><span class="va">True</span>, bins<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Age Distribution by Group'</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Age'</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Count'</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot: Baseline Systolic BP</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">4</span>))</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>sns.boxplot(data<span class="op">=</span>df1, x<span class="op">=</span><span class="st">'Group'</span>, y<span class="op">=</span><span class="st">'Baseline_SBP'</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Baseline Systolic Blood Pressure by Group'</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Systolic BP (mmHg)'</span>)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">''</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 3: Violin plot of Baseline Systolic BP</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">4</span>))</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>sns.violinplot(data<span class="op">=</span>df1, x<span class="op">=</span><span class="st">'Group'</span>, y<span class="op">=</span><span class="st">'Baseline_SBP'</span>, inner<span class="op">=</span><span class="st">'box'</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Violin Plot: Baseline Systolic Blood Pressure by Group'</span>)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Systolic BP (mmHg)'</span>)</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">''</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="interpretation-tips" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-tips">💡 Interpretation Tips</h3>
<ul>
<li><p>Look for symmetry or skewness.</p></li>
<li><p>Check for group overlap—similar distributions are a good sign of effective randomisation.</p></li>
<li><p>Use this to support your interpretation of Table 1.</p></li>
</ul>
<hr>
</section>
</section>
</section>
<section id="primary-endpoint-1" class="level1">
<h1>Primary endpoint</h1>
<section id="analysing-survival-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="analysing-survival-outcomes">🧬 Analysing Survival Outcomes</h2>
<p>The primary endpoint of the Hipponol trial is <strong>2-year survival</strong>, coded as:</p>
<ul>
<li>1 = **Survived</li>
<li>0 = <strong>Died during follow-up</strong></li>
</ul>
<p>Survival data is binary and typically analysed using methods suited to categorical outcomes or time-to-event data (e.g.&nbsp;Cox models, Kaplan–Meier). In our case, we assume <strong>binary survival</strong> at 2 years, so logistic regression is appropriate.</p>
<section id="quick-check-chi-squared-test-for-survival" class="level3">
<h3 class="anchored" data-anchor-id="quick-check-chi-squared-test-for-survival">🧪 Quick Check: Chi-squared Test for Survival</h3>
<p>Before diving into regression models, we can start with a simple comparison of survival rates between the Hipponol and Control groups using a Chi-squared test.</p>
<p>✅ Why use it?</p>
<ul>
<li>It’s a straightforward way to compare <strong>proportions</strong> between two groups.</li>
<li>Useful for <strong>binary outcomes</strong> like survival (1 = survived, 0 = died).</li>
<li>Helps confirm whether survival rates differ <strong>significantly</strong> between the two groups.</li>
</ul>
<p>🧾 Method</p>
<p>We use a <strong>contingency table</strong> to count survivors and non-survivors in each group, then apply the <strong>Chi-squared test of independence</strong>:</p>
<div id="cf34f731" class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>contingency <span class="op">=</span> pd.crosstab(df1[<span class="st">'Group'</span>], df1[<span class="st">'Survival'</span>])</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>chi2, p, dof, expected <span class="op">=</span> chi2_contingency(contingency)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Contingency Table:"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(contingency)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Chi-squared test p-value: </span><span class="sc">{</span>p<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>📌 Interpretation</p>
<ul>
<li>A <strong>small p-value</strong> (typically &lt; 0.05) suggests a <strong>statistically significant</strong> difference in survival between groups.</li>
<li>This test <strong>does not account for confounders</strong> like age or smoking — use logistic regression for that.</li>
</ul>
</section>
</section>
<section id="logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression">🔎 Logistic Regression</h2>
<p>Once we’ve done a basic comparison (like a Chi-squared test), the next step is a <strong>logistic regression</strong>. This lets us model the probability of survival while also:</p>
<ul>
<li>Controlling for other variables (e.g.&nbsp;age, smoking)</li>
<li>Estimating odds ratios, which are easier to interpret than raw coefficients</li>
</ul>
<section id="what-is-logistic-regression" class="level3">
<h3 class="anchored" data-anchor-id="what-is-logistic-regression">💡 What is logistic regression?</h3>
<p>Logistic regression is used when your outcome is <strong>binary</strong> — in this case, survival (<code>1</code>) vs.&nbsp;death (<code>0</code>). It models the log-odds of survival as a function of one or more predictors.</p>
<div id="6f9a7a13" class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a logistic regression model</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>logit_model <span class="op">=</span> smf.logit(<span class="st">'Survival ~ Group'</span>, data<span class="op">=</span>df1).fit()</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(logit_model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>🔁 From log-odds to odds ratio</p>
<p>The model estimates <strong>log-odds</strong>, which are not intuitive. We convert them to <strong>odds ratios</strong> using the exponential function:</p>
<div id="692dbfaf" class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>odds_ratios <span class="op">=</span> logit_model.params.<span class="bu">apply</span>(np.exp)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(odds_ratios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>An odds ratio (OR):</p>
<ul>
<li>= 1 means no effect</li>
<li><blockquote class="blockquote">
<p>1 means increased odds (e.g.&nbsp;Hipponol improves survival)</p>
</blockquote></li>
<li>&lt; 1 means reduced odds (e.g.&nbsp;Hipponol worsens survival)</li>
</ul>
</section>
<section id="example-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="example-interpretation">📌 Example Interpretation</h3>
<p>If <code>Group[T.Hipponol]</code> has an OR of <code>1.6</code>:</p>
<blockquote class="blockquote">
<p>“Participants in the Hipponol group had 60% higher odds of surviving the 2-year follow-up compared to the control group.”</p>
</blockquote>
</section>
<section id="optional-add-other-variables" class="level3">
<h3 class="anchored" data-anchor-id="optional-add-other-variables">📎 Optional: Add other variables</h3>
<p>You can also control for age, sex, and smoking:</p>
<div id="86001f5b" class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>logit_full <span class="op">=</span> smf.logit(<span class="st">'Survival ~ Group + Age + C(Sex) + C(SmokingStatus)'</span>, data<span class="op">=</span>df1).fit()</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(logit_full.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This gives you adjusted odds ratios — a better estimate when multiple factors influence the outcome.</p>
</section>
<section id="confidence-intervals-for-odds-ratios" class="level3">
<h3 class="anchored" data-anchor-id="confidence-intervals-for-odds-ratios">📏 Confidence Intervals for Odds Ratios</h3>
<p>When you run a logistic regression, the model provides <strong>standard errors</strong> for the coefficients. You can use these to calculate a 95% confidence interval (CI) for each odds ratio:</p>
<div id="c51f2dcd" class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get confidence intervals for the log-odds</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>conf <span class="op">=</span> logit_model.conf_int()</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>conf.columns <span class="op">=</span> [<span class="st">'2.5%'</span>, <span class="st">'97.5%'</span>]</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Add odds ratios</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>conf_exp <span class="op">=</span> np.exp(conf)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>conf_exp[<span class="st">'Odds Ratio'</span>] <span class="op">=</span> np.exp(logit_model.params)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(conf_exp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="how-to-interpret-this" class="level3">
<h3 class="anchored" data-anchor-id="how-to-interpret-this">🧠 How to interpret this:</h3>
<p>If the 95% CI for an odds ratio: - Includes 1, the result is <strong>not statistically significant</strong> at p &lt; 0.05 - Excludes 1, then the effect is <strong>statistically significant</strong></p>
</section>
<section id="example" class="level3">
<h3 class="anchored" data-anchor-id="example">📌 Example:</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>OR</th>
<th>2.5%</th>
<th>97.5%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Group[T.Hipponol]</td>
<td>1.62</td>
<td>1.02</td>
<td>2.58</td>
</tr>
</tbody>
</table>
<hr>
<blockquote class="blockquote">
<p>_“The odds of survival in the Hipponol group are 62% higher than in the control group (95% CI: 1.02–2.58).”</p>
</blockquote>
<p>This suggests a <strong>statistically significant effect</strong>, as the interval does not include 1.</p>
</section>
</section>
<section id="bayesian-logistic-regression-survival" class="level2">
<h2 class="anchored" data-anchor-id="bayesian-logistic-regression-survival">Bayesian Logistic Regression – Survival</h2>
<p>In this section, we apply <strong>Bayesian logistic regression</strong> to evaluate whether assignment to the <strong>Hipponol</strong> group affects the <strong>probability of survival</strong> compared to the <strong>Control</strong> group.</p>
<p>This analysis complements the Frequentist approach by offering a full <strong>posterior distribution</strong> of the treatment effect, providing a probabilistic interpretation of results rather than just point estimates and p-values.</p>
<section id="why-bayesian" class="level3">
<h3 class="anchored" data-anchor-id="why-bayesian">🧮 Why Bayesian?</h3>
<p>Bayesian modelling is particularly useful when:</p>
<ul>
<li>You want <strong>probabilistic interpretations</strong> of effect size.</li>
<li>You have <strong>prior knowledge</strong> you wish to incorporate.</li>
<li>You want a <strong>posterior distribution</strong> instead of a point estimate.</li>
<li>You’re dealing with <strong>small samples</strong>, where Frequentist power is limited.</li>
</ul>
<p>In our case, we use <strong>weakly informative</strong> priors (e.g.&nbsp;Normal(0, 10)) to express general uncertainty without strong assumptions.</p>
<hr>
</section>
<section id="goal" class="level3">
<h3 class="anchored" data-anchor-id="goal">🎯 Goal</h3>
<p>We aim to:</p>
<ul>
<li>Estimate the <strong>posterior probability distribution</strong> of the survival effect due to Hipponol.</li>
<li>Quantify the <strong>uncertainty</strong> in this effect.</li>
<li>Calculate the <strong>posterior odds ratio</strong> for survival in the Hipponol group compared to Control.</li>
</ul>
<p>Bayesian inference allows us to express the result as:</p>
<blockquote class="blockquote">
<p><em>“There is a XX% probability that Hipponol increases survival compared to control.”</em></p>
</blockquote>
<p>This is fundamentally different from the Frequentist interpretation, which only tells us the probability of observing our data under the null hypothesis.</p>
<hr>
</section>
<section id="define-predictor-and-outcome" class="level3">
<h3 class="anchored" data-anchor-id="define-predictor-and-outcome">📦 Define Predictor and Outcome</h3>
<p>To build our model, we first define the <strong>predictor</strong> (treatment group) and <strong>outcome</strong> (survival).</p>
<ul>
<li><p><code>X</code>: A binary predictor indicating group membership<br>
<code>0 = Control</code>, <code>1 = Hipponol</code></p></li>
<li><p><code>y</code>: A binary outcome<br>
<code>0 = Did not survive</code>, <code>1 = Survived</code></p></li>
</ul>
<p>This mirrors the structure required for <strong>Bernoulli trials</strong>, where each observation represents a binary outcome.</p>
<div id="693f648a" class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert group to numeric: 0 = Control, 1 = Hipponol</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> (df[<span class="st">'Group'</span>] <span class="op">==</span> <span class="st">'Hipponol'</span>).astype(<span class="bu">int</span>).values</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Survival outcome: already coded as 0 = no, 1 = yes</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">'Survival'</span>].astype(<span class="bu">int</span>).values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we build and fit the Bayesian model using PyMC.</p>
</section>
</section>
<section id="step-by-step-bayesian-logistic-regression-in-pymc" class="level2">
<h2 class="anchored" data-anchor-id="step-by-step-bayesian-logistic-regression-in-pymc">🔧 Step-by-Step: Bayesian Logistic Regression in PyMC</h2>
<p>We now construct and sample from a <strong>Bayesian logistic regression model</strong> using <code>PyMC</code>. This model estimates the effect of group assignment (Hipponol vs Control) on the probability of survival.</p>
<hr>
<section id="model-structure" class="level3">
<h3 class="anchored" data-anchor-id="model-structure">📐 Model Structure</h3>
<ol type="1">
<li><strong>Data</strong>:
<ul>
<li><code>x_shared</code>: Encodes treatment group (0 = Control, 1 = Hipponol)<br>
</li>
<li><code>y_shared</code>: Binary survival outcome (0 = no, 1 = yes)</li>
</ul></li>
<li><strong>Priors</strong>:
<ul>
<li><code>Intercept</code>: Prior belief about survival probability in the Control group.<br>
→ Set as <code>Normal(0, 10)</code> to reflect wide uncertainty.</li>
<li><code>Beta_Group</code>: Prior for the effect of the Hipponol group.<br>
→ Also <code>Normal(0, 10)</code> (can be tightened if prior knowledge exists).</li>
</ul></li>
<li><strong>Logistic function</strong>:
<ul>
<li>Computes log-odds: <code>logit_p = intercept + beta_group * x_shared</code><br>
</li>
<li>Converts to probability via sigmoid: <code>p = sigmoid(logit_p)</code></li>
</ul></li>
<li><strong>Likelihood</strong>:
<ul>
<li>Models observed survival data as a Bernoulli trial with success probability <code>p</code>.</li>
</ul></li>
<li><strong>Sampling</strong>:
<ul>
<li>We use Hamiltonian Monte Carlo (HMC) via the NUTS sampler.<br>
</li>
<li>4 chains × 2000 draws each, with 1000 tuning samples per chain.</li>
</ul></li>
</ol>
<hr>
</section>
<section id="pymc-model-code" class="level3">
<h3 class="anchored" data-anchor-id="pymc-model-code">📦 PyMC Model Code</h3>
<div id="3654f1d5" class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> pm.Model() <span class="im">as</span> model:</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Data containers (for flexibility in updating)</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    x_shared <span class="op">=</span> pm.Data(<span class="st">"x_shared"</span>, X)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    y_shared <span class="op">=</span> pm.Data(<span class="st">"y_shared"</span>, y)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Priors</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    intercept <span class="op">=</span> pm.Normal(<span class="st">"Intercept"</span>, mu<span class="op">=</span><span class="dv">0</span>, sigma<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    beta_group <span class="op">=</span> pm.Normal(<span class="st">"Beta_Group"</span>, mu<span class="op">=</span><span class="dv">0</span>, sigma<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Logistic function</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    logit_p <span class="op">=</span> intercept <span class="op">+</span> beta_group <span class="op">*</span> x_shared</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> pm.Deterministic(<span class="st">"p"</span>, pm.math.sigmoid(logit_p))</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Likelihood</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    y_obs <span class="op">=</span> pm.Bernoulli(<span class="st">"y_obs"</span>, p<span class="op">=</span>p, observed<span class="op">=</span>y_shared)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Sampling from the posterior</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    trace <span class="op">=</span> pm.sample(<span class="dv">2000</span>, tune<span class="op">=</span><span class="dv">1000</span>, target_accept<span class="op">=</span><span class="fl">0.95</span>, return_inferencedata<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>🔍 Next Steps After sampling, we will:</p>
<ul>
<li><strong>Inspect the posterior</strong> of Beta_Group to assess the treatment effect.</li>
<li><strong>Convert</strong> this to an <strong>odds ratio</strong> (by exponentiating Beta_Group).</li>
<li><strong>Visualise</strong> the posterior distribution using <code>arviz</code>.</li>
</ul>
<div id="510711a4" class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot posterior for Beta_Group</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>az.plot_posterior(trace, var_names<span class="op">=</span>[<span class="st">'Beta_Group'</span>], ref_val<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Posterior Distribution: Group Effect (log-odds)"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to odds ratio</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>odds_ratios <span class="op">=</span> np.exp(trace.posterior[<span class="st">'Beta_Group'</span>].values.flatten())</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot posterior odds ratio</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>az.plot_posterior(odds_ratios, ref_val<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Posterior Odds Ratio: Hipponol vs Control"</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Odds Ratio"</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">🧠 Interpretation</h3>
<ul>
<li>If the <strong>posterior</strong> of Beta_Group is mostly above 0 → <strong>Hipponol increases odds of survival</strong>.</li>
<li>If the <strong>95% credible interval (HDI)</strong> for odds_ratios excludes 1 → <strong>strong evidence for a difference</strong>.</li>
</ul>
<p>You can compute az.hdi() for numeric intervals:</p>
<div id="3403e234" class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>az.hdi(odds_ratios, hdi_prob<span class="op">=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>✅ This Bayesian approach allows for <strong>direct probability statements</strong>:</p>
<p>“There is a 95% probability that Hipponol increases the odds of survival by X–Y%.”</p>
</section>
</section>
<section id="kaplanmeier-survival-curves" class="level2">
<h2 class="anchored" data-anchor-id="kaplanmeier-survival-curves">📈 Kaplan–Meier Survival Curves</h2>
<p>To visualise how survival changes over time in each group, we use <strong>Kaplan–Meier survival estimates</strong>. These curves provide a non-parametric estimate of the survival function, which reflects the probability of survival beyond a given time point.</p>
<section id="why-kaplanmeier" class="level3">
<h3 class="anchored" data-anchor-id="why-kaplanmeier">🔍 Why Kaplan–Meier?</h3>
<p>Kaplan–Meier curves are ideal for visualising time-to-event data because they:</p>
<ul>
<li>Handle censored data (participants who didn’t experience the event by the end of follow-up)</li>
<li>Show the proportion of participants surviving over time</li>
<li>Allow intuitive comparison between groups (e.g.&nbsp;Hipponol vs Control)</li>
</ul>
</section>
<section id="interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-1">📘 Interpretation</h3>
<p>Each drop in the curve corresponds to an event (e.g.&nbsp;death). A steeper decline indicates more frequent events, whereas a flat curve suggests stable survival.</p>
<p>If the curves for the two groups diverge:</p>
<ul>
<li><strong>Wider separation</strong> may indicate a meaningful difference in survival.</li>
<li><strong>Overlap</strong> suggests similar survival patterns.</li>
</ul>
<div id="b80b4e52" class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Split data</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>df_control <span class="op">=</span> df[df[<span class="st">'Group'</span>] <span class="op">==</span> <span class="st">'Control'</span>]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>df_hipponol <span class="op">=</span> df[df[<span class="st">'Group'</span>] <span class="op">==</span> <span class="st">'Hipponol'</span>]</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialise fitter</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>kmf_control <span class="op">=</span> KaplanMeierFitter()</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>kmf_hipponol <span class="op">=</span> KaplanMeierFitter()</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit and plot</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>kmf_control.fit(durations<span class="op">=</span>df_control[<span class="st">'Time_to_Event'</span>],</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>                event_observed<span class="op">=</span>df_control[<span class="st">'Survival'</span>],</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>                label<span class="op">=</span><span class="st">'Control'</span>)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>kmf_control.plot_survival_function(ci_show<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>kmf_hipponol.fit(durations<span class="op">=</span>df_hipponol[<span class="st">'Time_to_Event'</span>],</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>                 event_observed<span class="op">=</span>df_hipponol[<span class="st">'Survival'</span>],</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>                 label<span class="op">=</span><span class="st">'Hipponol'</span>)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>kmf_hipponol.plot_survival_function(ci_show<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Kaplan–Meier Survival Curves by Group"</span>)</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Time to Event (months)"</span>)</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Survival Probability"</span>)</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="compare-groups-statistically-log-rank-test" class="level2">
<h2 class="anchored" data-anchor-id="compare-groups-statistically-log-rank-test">🧪 Compare groups statistically – Log-rank test</h2>
<p>This checks whether the survival distributions are significantly different between the groups.</p>
<section id="what-is-the-log-rank-test" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-log-rank-test">🔍 What is the Log-Rank Test?</h3>
<p>The <strong>log-rank test</strong> is a non-parametric statistical test used to compare the survival distributions of two or more groups. It’s particularly useful in clinical trials or studies with time-to-event data.</p>
<p>✅ What it does:</p>
<ul>
<li>Compares the observed number of events in each group to the expected number under the null hypothesis (that all groups have the same survival curve).</li>
<li>It handles <strong>censored data</strong> properly.</li>
<li>Outputs a <strong>p-value</strong>: if this is small (typically &lt; 0.05), it suggests the survival curves differ significantly.</li>
</ul>
<div id="b035e8ea" class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter your data</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>df_control <span class="op">=</span> df[df[<span class="st">"Group"</span>] <span class="op">==</span> <span class="st">"Control"</span>]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>df_hipponol <span class="op">=</span> df[df[<span class="st">"Group"</span>] <span class="op">==</span> <span class="st">"Hipponol"</span>]</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the log-rank test</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> logrank_test(</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    df_control[<span class="st">"Time_to_Event"</span>], df_hipponol[<span class="st">"Time_to_Event"</span>],</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    event_observed_A<span class="op">=</span>df_control[<span class="st">"Survival"</span>],</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    event_observed_B<span class="op">=</span>df_hipponol[<span class="st">"Survival"</span>]</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the results</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"📈 Log-rank test between Control and Hipponol:"</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Test statistic: </span><span class="sc">{</span>results<span class="sc">.</span>test_statistic<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-value: </span><span class="sc">{</span>results<span class="sc">.</span>p_value<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Optional: simple interpretation</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> results.p_value <span class="op">&lt;</span> <span class="fl">0.05</span>:</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"⚠️ There is a significant difference in survival between groups."</span>)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"✅ No significant difference in survival between groups."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="when-to-use" class="level3">
<h3 class="anchored" data-anchor-id="when-to-use">🧪 When to Use:</h3>
<p>Use this when:</p>
<ul>
<li>You’ve plotted Kaplan-Meier curves and want to <strong>test if the difference is significant</strong>.</li>
<li>You’re evaluating <strong>intervention effects</strong> in RCTs or cohort studies.</li>
<li>You want a simple test without assuming specific hazard functions (unlike Cox models).</li>
</ul>
</section>
</section>
<section id="cox-proportional-hazards-model-a-detailed-guide" class="level2">
<h2 class="anchored" data-anchor-id="cox-proportional-hazards-model-a-detailed-guide">Cox Proportional Hazards Model: A Detailed Guide</h2>
<section id="what-is-the-cox-proportional-hazards-model" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-cox-proportional-hazards-model">✅ What Is the Cox Proportional Hazards Model?</h3>
<p>The <strong>Cox PH model</strong> is a <strong>semi-parametric regression model</strong> used in survival analysis. It relates the time that passes before an event occurs to <strong>one or more covariates</strong>.</p>
</section>
<section id="core-idea" class="level3">
<h3 class="anchored" data-anchor-id="core-idea">Core idea:</h3>
<p>It models the <strong>hazard rate</strong> at time <em>t</em> as:</p>
<p>[ h(t|X) = h_0(t) (_1X_1 + _2X_2 + + _pX_p) ]</p>
<ul>
<li>( h_0(t) ) is the <strong>baseline hazard</strong> (unspecified)</li>
<li>( X_i ) are the covariates (e.g.&nbsp;Group, Age, Sex)</li>
<li>( _i ) are coefficients estimated from the data</li>
</ul>
<p>The model makes the <strong>proportional hazards assumption</strong>: the ratio of hazards between groups is constant over time.</p>
<hr>
</section>
</section>
<section id="how-to-fit-it-in-python-with-lifelines" class="level2">
<h2 class="anchored" data-anchor-id="how-to-fit-it-in-python-with-lifelines">🛠️ 2. How to Fit It in Python (with <code>lifelines</code>)</h2>
<div id="e6b016fb" class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select relevant columns only</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>df_cox <span class="op">=</span> df[[<span class="st">"Age"</span>, <span class="st">"Sex"</span>, <span class="st">"SmokingStatus"</span>, <span class="st">"Group"</span>, <span class="st">"Time_to_Event"</span>, <span class="st">"Survival"</span>]].copy()</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># One-hot encode categorical variables, dropping first category to avoid multicollinearity</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>df_cox <span class="op">=</span> pd.get_dummies(df_cox, drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the Cox model</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>cph <span class="op">=</span> CoxPHFitter()</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>cph.fit(df_cox, duration_col<span class="op">=</span><span class="st">"Time_to_Event"</span>, event_col<span class="op">=</span><span class="st">"Survival"</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>cph.print_summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="how-to-interpret-the-output" class="level3">
<h3 class="anchored" data-anchor-id="how-to-interpret-the-output">📏 How to Interpret the Output</h3>
<p>The summary table includes:</p>
<ul>
<li><code>coef</code>: log of the hazard ratio (HR)</li>
<li><code>exp(coef)</code>: the <strong>hazard ratio</strong></li>
<li><code>p</code>: p-value testing if the coefficient is significantly different from 0</li>
<li><code>-log2(p)</code>: significance in a log-scale</li>
<li><code>95% CI</code>: confidence intervals for the HR</li>
</ul>
</section>
<section id="example-interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="example-interpretation-1">Example Interpretation:</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 18%">
<col style="width: 15%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>exp(coef)</th>
<th>p-value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Group_Hipponol</td>
<td>0.65</td>
<td>0.001</td>
<td>Hipponol <strong>reduces</strong> the hazard by 35% vs.&nbsp;Control</td>
</tr>
<tr class="even">
<td>Age</td>
<td>1.02</td>
<td>0.050</td>
<td>Each year of age <strong>increases</strong> hazard by 2%</td>
</tr>
<tr class="odd">
<td>Sex_Male</td>
<td>1.10</td>
<td>0.200</td>
<td>No significant difference vs.&nbsp;Female</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="test-the-proportional-hazards-ph-assumption" class="level3">
<h3 class="anchored" data-anchor-id="test-the-proportional-hazards-ph-assumption">⚠️ Test the Proportional Hazards (PH) Assumption</h3>
<p>This is <strong>essential</strong> because if PH is violated, your hazard ratios are <strong>not valid over time</strong>.</p>
<div id="a40dc705" class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check proportional hazards assumption</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>cph.check_assumptions(df_cox, p_value_threshold<span class="op">=</span><span class="fl">0.05</span>, show_plots<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Print a test result for each covariate</li>
<li>Show <strong>Schoenfeld residuals</strong> plots:
<ul>
<li>If residuals show <strong>systematic trends</strong>, PH is <strong>likely violated</strong></li>
<li>Flat residuals = good</li>
</ul></li>
</ul>
</section>
<section id="if-ph-is-violated" class="level3">
<h3 class="anchored" data-anchor-id="if-ph-is-violated">If PH is violated:</h3>
<ul>
<li>Add <strong>interaction terms with time</strong></li>
<li>Use <strong>stratified Cox models</strong></li>
<li>Split time into intervals (time-dependent covariates)</li>
</ul>
</section>
<section id="optional-predict-or-visualise" class="level3">
<h3 class="anchored" data-anchor-id="optional-predict-or-visualise">🧪 5. (Optional) Predict or Visualise</h3>
<p>You can predict survival curves for a given profile:</p>
<div id="e1097f76" class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a base profile (mean age, female, non-smoker)</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>base <span class="op">=</span> pd.DataFrame({</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Age'</span>: [df[<span class="st">'Age'</span>].mean()],</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Sex_Male'</span>: [<span class="dv">0</span>],</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'SmokingStatus_Smoker'</span>: [<span class="dv">0</span>],</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Group_Hipponol'</span>: [<span class="dv">0</span>]  <span class="co"># Control group</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Copy and modify for Hipponol</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>hipponol <span class="op">=</span> base.copy()</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>hipponol[<span class="st">'Group_Hipponol'</span>] <span class="op">=</span> <span class="dv">1</span>  <span class="co"># Switch to Hipponol group</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict survival curves</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>sf_control <span class="op">=</span> cph.predict_survival_function(base)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>sf_hipponol <span class="op">=</span> cph.predict_survival_function(hipponol)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>plt.plot(sf_control, label<span class="op">=</span><span class="st">"Control"</span>)</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>plt.plot(sf_hipponol, label<span class="op">=</span><span class="st">"Hipponol"</span>)</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Predicted Survival Curve for Control vs. Hipponol"</span>)</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Time"</span>)</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Survival Probability"</span>)</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="secondary-endpoint-blood-pressure-change" class="level1">
<h1>🧪 Secondary Endpoint: Blood Pressure Change</h1>
<p>This section explores how to compare systolic blood pressure (SBP) outcomes between the treatment group (<code>Hipponol</code>) and the control group. SBP is treated as a ↪continuous variable, and we are particularly interested in:</p>
<ul>
<li>Whether there are baseline differences</li>
<li>Whether the groups differ at follow-up</li>
<li>Whether <strong>Hipponol</strong> leads to a greater reduction in SBP than the control</li>
</ul>
<hr>
<section id="visual-exploration-of-distributions" class="level2">
<h2 class="anchored" data-anchor-id="visual-exploration-of-distributions">1. 🎨 Visual Exploration of Distributions</h2>
<p>Before diving into formal tests, it’s useful to examine the data visually. You can compare the SBP distributions for the two groups at:</p>
<section id="baseline" class="level3">
<h3 class="anchored" data-anchor-id="baseline">Baseline</h3>
<div id="f49cdc42" class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set aesthetic style</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>(style<span class="op">=</span><span class="st">"whitegrid"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># KDE plot: Baseline SBP</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>sns.kdeplot(data<span class="op">=</span>df, x<span class="op">=</span><span class="st">'Baseline_SBP'</span>, hue<span class="op">=</span><span class="st">'Group'</span>, fill<span class="op">=</span><span class="va">True</span>, common_norm<span class="op">=</span><span class="va">False</span>, alpha<span class="op">=</span><span class="fl">0.4</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Baseline Systolic BP Distribution by Group"</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Baseline SBP (mmHg)"</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="follow-up" class="level3">
<h3 class="anchored" data-anchor-id="follow-up">Follow-up</h3>
<div id="ba7a54c6" class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># KDE plot: Follow-up SBP</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>sns.kdeplot(data<span class="op">=</span>df, x<span class="op">=</span><span class="st">'Followup_SBP'</span>, hue<span class="op">=</span><span class="st">'Group'</span>, fill<span class="op">=</span><span class="va">True</span>, common_norm<span class="op">=</span><span class="va">False</span>, alpha<span class="op">=</span><span class="fl">0.4</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Follow-up Systolic BP Distribution by Group"</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Follow-up SBP (mmHg)"</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="change-in-blood-pressure" class="level3">
<h3 class="anchored" data-anchor-id="change-in-blood-pressure">Change in Blood Pressure</h3>
<div id="58f5973d" class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate and plot SBP change</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'SBP_change'</span>] <span class="op">=</span> df[<span class="st">'Followup_SBP'</span>] <span class="op">-</span> df[<span class="st">'Baseline_SBP'</span>]</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>sns.kdeplot(data<span class="op">=</span>df, x<span class="op">=</span><span class="st">'SBP_change'</span>, hue<span class="op">=</span><span class="st">'Group'</span>, fill<span class="op">=</span><span class="va">True</span>, common_norm<span class="op">=</span><span class="va">False</span>, alpha<span class="op">=</span><span class="fl">0.4</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Change in SBP (Follow-up – Baseline) by Group"</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Change in SBP (mmHg)"</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="t-test-for-comparing-change-in-sbp-between-two-groups" class="level2">
<h2 class="anchored" data-anchor-id="t-test-for-comparing-change-in-sbp-between-two-groups">🔍 t-Test for Comparing Change in SBP Between Two Groups</h2>
<section id="what-is-it" class="level3">
<h3 class="anchored" data-anchor-id="what-is-it">What is it?</h3>
<p>A <strong>two-sample t-test</strong> (also called an <strong>independent samples t-test</strong>) is used to determine whether there is a <strong>statistically significant difference</strong> in the <strong>means ↪of a continuous variable</strong> between two <strong>independent groups</strong>.</p>
<p>In this case, we’re interested in:</p>
<blockquote class="blockquote">
<p><strong>Is the average change in SBP significantly different between participants in the Control group and those in the Hipponol group?</strong></p>
</blockquote>
<hr>
</section>
<section id="when-to-use-it" class="level3">
<h3 class="anchored" data-anchor-id="when-to-use-it">🧪 When to use it</h3>
<p>Use a two-sample t-test when: - The outcome variable (here: <code>SBP change = Followup_SBP − Baseline_SBP</code>) is continuous. - The two groups are <strong>independent</strong> (no participant is in both groups). - The data are approximately <strong>normally distributed</strong> in each group. - Variances are assumed to be <strong>equal</strong> (although Welch’s correction can be used otherwise).</p>
<hr>
</section>
<section id="hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="hypotheses">🧠 Hypotheses</h3>
<p>Let: - $ _1 $: mean change in SBP in the <strong>Control</strong> group - $ _2 $: mean change in SBP in the <strong>Hipponol</strong> group</p>
<p>Then:</p>
<ul>
<li><strong>Null hypothesis $ H_0 $</strong>: $ _1 = _2 $ (no difference)</li>
<li><strong>Alternative hypothesis $ H_A $</strong>: $ _1 _2 $ (there is a difference)</li>
</ul>
<p>You can also use a <strong>one-sided test</strong> if you expect Hipponol to reduce SBP.</p>
<hr>
<div id="23674baa" class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>hip <span class="op">=</span> df[df[<span class="st">'Group'</span>] <span class="op">==</span> <span class="st">'Hipponol'</span>][<span class="st">'SBP_change'</span>]</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>con <span class="op">=</span> df[df[<span class="st">'Group'</span>] <span class="op">==</span> <span class="st">'Control'</span>][<span class="st">'SBP_change'</span>]</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>con <span class="op">=</span> df[df[<span class="st">'Group'</span>] <span class="op">==</span> <span class="st">'Control'</span>][<span class="st">'SBP_change'</span>]</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean difference</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>diff <span class="op">=</span> hip.mean() <span class="op">-</span> con.mean()</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard error of the difference</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>se_diff <span class="op">=</span> np.sqrt(hip.var(ddof<span class="op">=</span><span class="dv">1</span>)<span class="op">/</span><span class="bu">len</span>(hip) <span class="op">+</span> con.var(ddof<span class="op">=</span><span class="dv">1</span>)<span class="op">/</span><span class="bu">len</span>(con))</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% Confidence Interval</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>dof <span class="op">=</span> <span class="bu">len</span>(hip) <span class="op">+</span> <span class="bu">len</span>(con) <span class="op">-</span> <span class="dv">2</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>ci <span class="op">=</span> stats.t.interval(<span class="fl">0.95</span>, dof, loc<span class="op">=</span>diff, scale<span class="op">=</span>se_diff)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="co"># t-test</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>t_stat, p_val <span class="op">=</span> ttest_ind(hip, con)</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Mean difference: </span><span class="sc">{</span>diff<span class="sc">:.2f}</span><span class="ss"> mmHg"</span>)</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"95% CI: </span><span class="sc">{</span>ci<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"t-statistic: </span><span class="sc">{</span>t_stat<span class="sc">:.3f}</span><span class="ss">, p-value: </span><span class="sc">{</span>p_val<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="interpreting-results" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-results">🧾 Interpreting results</h2>
<ul>
<li>A <strong>small p-value</strong> (typically &lt; 0.05) means you reject the null hypothesis and conclude that <strong>SBP change differs significantly</strong> between the groups.</li>
<li>A <strong>large p-value</strong> suggests that the observed difference might be due to chance.</li>
</ul>
</section>
<section id="anova-and-ancova" class="level2">
<h2 class="anchored" data-anchor-id="anova-and-ancova">🧪 ANOVA and ANCOVA</h2>
<section id="analysis-of-variance-anova" class="level3">
<h3 class="anchored" data-anchor-id="analysis-of-variance-anova">Analysis of Variance (ANOVA)</h3>
<p><strong>ANOVA</strong> is used to determine whether there are statistically significant differences in the means of a continuous variable across two or more groups.</p>
<p>In our case, we can use <strong>one-way ANOVA</strong> to compare the change in systolic blood pressure (SBP) between the <code>Control</code> and <code>Hipponol</code> groups.</p>
</section>
<section id="assumptions" class="level3">
<h3 class="anchored" data-anchor-id="assumptions">🔍 Assumptions:</h3>
<ul>
<li>Independence of observations</li>
<li>Normally distributed SBP changes within each group</li>
<li>Homogeneity of variances across groups</li>
</ul>
<div id="7c8b5498" class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assume df is your DataFrame and has already loaded the dataset</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'SBP_Change'</span>] <span class="op">=</span> df[<span class="st">'Followup_SBP'</span>] <span class="op">-</span> df[<span class="st">'Baseline_SBP'</span>]</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Split by group</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>control <span class="op">=</span> df[df[<span class="st">'Group'</span>] <span class="op">==</span> <span class="st">'Control'</span>][<span class="st">'SBP_Change'</span>]</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>hipponol <span class="op">=</span> df[df[<span class="st">'Group'</span>] <span class="op">==</span> <span class="st">'Hipponol'</span>][<span class="st">'SBP_Change'</span>]</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Run one-way ANOVA</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>f_stat, p_value <span class="op">=</span> stats.f_oneway(control, hipponol)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"One-way ANOVA"</span>)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"F-statistic: </span><span class="sc">{</span>f_stat<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"P-value: </span><span class="sc">{</span>p_value<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="comparison-t-test-vs.-anova" class="level3">
<h3 class="anchored" data-anchor-id="comparison-t-test-vs.-anova">🧪 Comparison: t-test vs.&nbsp;ANOVA</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th><strong>t-test</strong></th>
<th><strong>ANOVA (one-way)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Use case</strong></td>
<td>Comparing <strong>two</strong> group means</td>
<td>Designed for comparing <strong>three or more</strong></td>
</tr>
<tr class="even">
<td><strong>Statistic reported</strong></td>
<td><em>t</em>-statistic</td>
<td><em>F</em>-statistic</td>
</tr>
<tr class="odd">
<td><strong>P-value</strong></td>
<td>Same as ANOVA when only 2 groups</td>
<td>Same as t-test when only 2 groups</td>
</tr>
<tr class="even">
<td><strong>Interpretation</strong></td>
<td>Mean difference</td>
<td>Variance between vs.&nbsp;within groups</td>
</tr>
<tr class="odd">
<td><strong>Extension</strong></td>
<td>Needs other models for &gt;2 groups</td>
<td>Naturally extends to &gt;2 group comparisons</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="mathematical-note" class="level2">
<h2 class="anchored" data-anchor-id="mathematical-note">📐 Mathematical Note</h2>
<p>When there are exactly <strong>two groups</strong>, the relationship between the statistics is:</p>
<p><span class="math display">\[
F = t^2
\]</span></p>
<p>So the numerical <strong>p-value</strong> and the result will be identical — the difference is in the formulation.</p>
<hr>
</section>
<section id="when-to-use-each" class="level2">
<h2 class="anchored" data-anchor-id="when-to-use-each">✅ When to Use Each?</h2>
<ul>
<li>✅ <strong>Use t-test</strong>: when you are only comparing two groups and want the simplest approach.</li>
<li>✅ <strong>Use ANOVA</strong>: when you are planning to include more than two groups in future or need consistency in your analysis framework.</li>
</ul>
<hr>
</section>
<section id="practical-implication" class="level2">
<h2 class="anchored" data-anchor-id="practical-implication">🔄 Practical Implication</h2>
<p>For the SBP change analysis with just Control and Hipponol: - Both methods are valid and will return the same <strong>p-value</strong>. - ANOVA provides more flexibility later (e.g., adjusting for other factors via ANCOVA or general linear models).</p>
<section id="analysis-of-covariance-ancova" class="level3">
<h3 class="anchored" data-anchor-id="analysis-of-covariance-ancova">Analysis of Covariance (ANCOVA)</h3>
<p><strong>ANCOVA</strong> extends ANOVA by including one or more <strong>continuous covariates</strong> that may influence the dependent variable. This is particularly useful when there are baseline differences between groups (e.g.&nbsp;in baseline SBP).</p>
<p>In our context, ANCOVA allows us to compare the <strong>Follow-up SBP</strong>, adjusting for <strong>Baseline SBP</strong> as a covariate.</p>
<section id="why-use-ancova" class="level4">
<h4 class="anchored" data-anchor-id="why-use-ancova">💡 Why use ANCOVA?</h4>
<ul>
<li>It reduces residual variance, improving statistical power</li>
<li>It adjusts for potential imbalances in baseline values</li>
</ul>
</section>
<section id="assumptions-1" class="level4">
<h4 class="anchored" data-anchor-id="assumptions-1">🔍 Assumptions:</h4>
<ul>
<li>Same as ANOVA, plus:
<ul>
<li>Linearity between covariate and outcome</li>
<li>Homogeneity of regression slopes (no interaction between group and covariate)</li>
</ul></li>
</ul>
<div id="08b7d091" class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert Group to categorical if needed</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Group'</span>] <span class="op">=</span> df[<span class="st">'Group'</span>].astype(<span class="st">'category'</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit ANCOVA model</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">'Followup_SBP ~ Group + Baseline_SBP + Age + Sex + SmokingStatus'</span>, data<span class="op">=</span>df).fit()</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Show summary</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>📊 Notes</p>
<ul>
<li>ANOVA checks whether the mean changes in SBP differ between groups.</li>
<li>ANCOVA goes further by adjusting for baseline SBP, increasing statistical power and controlling for initial differences.</li>
</ul>
</section>
</section>
</section>
</section>
<section id="regression-analysis-blood-pressure-change" class="level1">
<h1>Regression Analysis: Blood Pressure Change</h1>
<p>To assess the relationship between treatment group and change in systolic blood pressure (SBP), a linear regression model can be used. This allows us to estimate the <strong>magnitude</strong> of the treatment effect while optionally adjusting for <strong>confounders</strong> like age, sex, and smoking status.</p>
<section id="step-1-compute-sbp-change" class="level4">
<h4 class="anchored" data-anchor-id="step-1-compute-sbp-change">📦 Step 1: Compute SBP Change</h4>
<div id="ce924317" class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'SBP_Change'</span>] <span class="op">=</span> df[<span class="st">'Followup_SBP'</span>] <span class="op">-</span> df[<span class="st">'Baseline_SBP'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-2-encode-the-treatment-group" class="level4">
<h4 class="anchored" data-anchor-id="step-2-encode-the-treatment-group">🔧 Step 2: Encode the Treatment Group</h4>
<p>To use <code>Group</code> in regression, convert it into a numeric variable. We’ll use <strong>0 = Control</strong>, <strong>1 = Hipponol</strong>.</p>
<div id="0262b997" class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Treatment'</span>] <span class="op">=</span> (df[<span class="st">'Group'</span>] <span class="op">==</span> <span class="st">'Hipponol'</span>).astype(<span class="bu">int</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-3-fit-the-regression-model" class="level4">
<h4 class="anchored" data-anchor-id="step-3-fit-the-regression-model">📊 Step 3: Fit the regression model</h4>
<p>This will estimate the <strong>mean difference in SBP change</strong> between the two groups. The intercept represents the mean change in the Control group, and the coefficient for <code>Treatment</code> represents the <strong>additional change</strong> for the Hipponol group.</p>
<div id="5c75414d" class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">'SBP_Change ~ Treatment'</span>, data<span class="op">=</span>df).fit()</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Show results</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-4-regression-with-covariates-optional" class="level2">
<h2 class="anchored" data-anchor-id="step-4-regression-with-covariates-optional">🧮 Step 4: Regression with Covariates (Optional)</h2>
<p>To adjust for potential confounders.</p>
<p>Note: <code>Sex</code> and <code>SmokingStatus</code> should be treated as categorical variables. You may need to encode them using <code>C()</code> in the formula:</p>
<div id="c8d6889e" class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>model_adj <span class="op">=</span> smf.ols(<span class="st">'SBP_Change ~ Treatment + Age + C(Sex) + C(SmokingStatus)'</span>, data<span class="op">=</span>df).fit()</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_adj.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="step-5-visualise-the-regression" class="level4">
<h4 class="anchored" data-anchor-id="step-5-visualise-the-regression">📈 Step 5: Visualise the Regression</h4>
<div id="de66aa91" class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Encode group as binary treatment (if not already done)</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Treatment'</span>] <span class="op">=</span> (df[<span class="st">'Group'</span>] <span class="op">==</span> <span class="st">'Hipponol'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Add jittered individual points</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>sns.stripplot(x<span class="op">=</span><span class="st">'Treatment'</span>, y<span class="op">=</span><span class="st">'SBP_Change'</span>, data<span class="op">=</span>df,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>              jitter<span class="op">=</span><span class="fl">0.2</span>, size<span class="op">=</span><span class="dv">5</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, color<span class="op">=</span><span class="st">'grey'</span>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Add group means and error bars (95% CI)</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>sns.pointplot(x<span class="op">=</span><span class="st">'Treatment'</span>, y<span class="op">=</span><span class="st">'SBP_Change'</span>, data<span class="op">=</span>df,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>              linestyle<span class="op">=</span><span class="st">'none'</span>, capsize<span class="op">=</span><span class="fl">0.1</span>, err_kws<span class="op">=</span>{<span class="st">'linewidth'</span>: <span class="fl">1.5</span>}, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Customise axes</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>plt.xticks([<span class="dv">0</span>, <span class="dv">1</span>], [<span class="st">'Control'</span>, <span class="st">'Hipponol'</span>])</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Change in Systolic Blood Pressure by Treatment Group'</span>)</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Treatment Group'</span>)</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Change in SBP (mmHg)'</span>)</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="interpretation-2" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-2">🧠 Interpretation</h3>
<ul>
<li>A <strong>negative coefficient</strong> for <code>Treatment</code> implies a greater <strong>reduction</strong> in SBP in the Hipponol group.</li>
<li>The <strong>p-value</strong> tells you whether this difference is statistically significant.</li>
<li>The <strong>adjusted R²</strong> provides an indication of how much variance in SBP change is explained by the model.</li>
</ul>
</section>
</section>
</section>
<section id="bayesian-regression-analysis-sbp-change" class="level1">
<h1>🧠 Bayesian Regression Analysis (SBP Change)</h1>
<p>This section uses a Bayesian approach to model the effect of treatment (<code>Hipponol</code> vs <code>Control</code>) on the change in systolic blood pressure (SBP), while adjusting for age, sex, and smoking status.</p>
<hr>
<section id="step-1-data-preparation" class="level4">
<h4 class="anchored" data-anchor-id="step-1-data-preparation">🧹 Step 1: Data Preparation</h4>
<p>First, we calculate the change in SBP and encode the categorical variables.</p>
<hr>
</section>
<section id="step-2-model-specification" class="level4">
<h4 class="anchored" data-anchor-id="step-2-model-specification">🧮 Step 2: Model Specification</h4>
<p>We model SBP change as a linear function of:</p>
<ul>
<li>Age (standardised)</li>
<li>Sex (Female as reference)</li>
<li>Smoking Status (Non-smoker as reference)</li>
<li>Group (Control as reference)</li>
</ul>
<div id="54c9330d" class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> scale_column(df, column, method<span class="op">=</span><span class="st">'zscore'</span>):</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Scales a column in the dataframe using the specified method.</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co">    - df: pandas DataFrame</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co">    - column: name of the column to scale</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="co">    - method: 'zscore', 'minmax', 'robust', or 'maxabs'</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="co">    - A pandas Series with the scaled values</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> df[column]</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> method <span class="op">==</span> <span class="st">'zscore'</span>:</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> (x <span class="op">-</span> x.mean()) <span class="op">/</span> x.std()</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> method <span class="op">==</span> <span class="st">'minmax'</span>:</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> (x <span class="op">-</span> x.<span class="bu">min</span>()) <span class="op">/</span> (x.<span class="bu">max</span>() <span class="op">-</span> x.<span class="bu">min</span>())</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> method <span class="op">==</span> <span class="st">'robust'</span>:</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>        median <span class="op">=</span> x.median()</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>        iqr <span class="op">=</span> x.quantile(<span class="fl">0.75</span>) <span class="op">-</span> x.quantile(<span class="fl">0.25</span>)</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> (x <span class="op">-</span> median) <span class="op">/</span> iqr</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> method <span class="op">==</span> <span class="st">'maxabs'</span>:</span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> x <span class="op">/</span> x.<span class="bu">abs</span>().<span class="bu">max</span>()</span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"Unknown scaling method. Choose 'zscore', 'minmax', 'robust', or 'maxabs'."</span>)</span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-31"><a href="#cb31-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Assume df is already loaded</span></span>
<span id="cb31-32"><a href="#cb31-32" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'SBP_Change'</span>] <span class="op">=</span> df[<span class="st">'Followup_SBP'</span>] <span class="op">-</span> df[<span class="st">'Baseline_SBP'</span>]</span>
<span id="cb31-33"><a href="#cb31-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-34"><a href="#cb31-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure proper one-hot encoding</span></span>
<span id="cb31-35"><a href="#cb31-35" aria-hidden="true" tabindex="-1"></a>df_encoded <span class="op">=</span> pd.get_dummies(df[[<span class="st">'SBP_Change'</span>, <span class="st">'Age'</span>, <span class="st">'Sex'</span>, <span class="st">'SmokingStatus'</span>, <span class="st">'Group'</span>]], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb31-36"><a href="#cb31-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-37"><a href="#cb31-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardise age</span></span>
<span id="cb31-38"><a href="#cb31-38" aria-hidden="true" tabindex="-1"></a>df_encoded[<span class="st">'Age_Standardised'</span>] <span class="op">=</span> scale_column(df_encoded, <span class="st">'Age'</span>)</span>
<span id="cb31-39"><a href="#cb31-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-40"><a href="#cb31-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the unstandardised 'Age' column if not needed</span></span>
<span id="cb31-41"><a href="#cb31-41" aria-hidden="true" tabindex="-1"></a>df_encoded <span class="op">=</span> df_encoded.drop(columns<span class="op">=</span><span class="st">'Age'</span>)</span>
<span id="cb31-42"><a href="#cb31-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-43"><a href="#cb31-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure all columns are float (important for PyMC)</span></span>
<span id="cb31-44"><a href="#cb31-44" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df_encoded.drop(columns<span class="op">=</span>[<span class="st">'SBP_Change'</span>]).astype(<span class="bu">float</span>)</span>
<span id="cb31-45"><a href="#cb31-45" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df_encoded[<span class="st">'SBP_Change'</span>].astype(<span class="bu">float</span>)</span>
<span id="cb31-46"><a href="#cb31-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-47"><a href="#cb31-47" aria-hidden="true" tabindex="-1"></a>predictor_names <span class="op">=</span> X.columns.tolist()</span>
<span id="cb31-48"><a href="#cb31-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-49"><a href="#cb31-49" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> pm.Model() <span class="im">as</span> model:</span>
<span id="cb31-50"><a href="#cb31-50" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Data containers</span></span>
<span id="cb31-51"><a href="#cb31-51" aria-hidden="true" tabindex="-1"></a>    predictors <span class="op">=</span> pm.Data(<span class="st">"predictors"</span>, X)</span>
<span id="cb31-52"><a href="#cb31-52" aria-hidden="true" tabindex="-1"></a>    outcome <span class="op">=</span> pm.Data(<span class="st">"outcome"</span>, y)</span>
<span id="cb31-53"><a href="#cb31-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-54"><a href="#cb31-54" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Priors</span></span>
<span id="cb31-55"><a href="#cb31-55" aria-hidden="true" tabindex="-1"></a>    intercept <span class="op">=</span> pm.Normal(<span class="st">"Intercept"</span>, mu<span class="op">=</span><span class="dv">0</span>, sigma<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb31-56"><a href="#cb31-56" aria-hidden="true" tabindex="-1"></a>    beta <span class="op">=</span> pm.Normal(<span class="st">"Beta"</span>, mu<span class="op">=</span><span class="dv">0</span>, sigma<span class="op">=</span><span class="dv">1</span>, shape<span class="op">=</span><span class="bu">len</span>(predictor_names))</span>
<span id="cb31-57"><a href="#cb31-57" aria-hidden="true" tabindex="-1"></a>    sigma <span class="op">=</span> pm.HalfNormal(<span class="st">"Sigma"</span>, sigma<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb31-58"><a href="#cb31-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-59"><a href="#cb31-59" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Linear model</span></span>
<span id="cb31-60"><a href="#cb31-60" aria-hidden="true" tabindex="-1"></a>    mu <span class="op">=</span> intercept <span class="op">+</span> pm.math.dot(predictors, beta)</span>
<span id="cb31-61"><a href="#cb31-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-62"><a href="#cb31-62" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Likelihood</span></span>
<span id="cb31-63"><a href="#cb31-63" aria-hidden="true" tabindex="-1"></a>    y_obs <span class="op">=</span> pm.Normal(<span class="st">"y_obs"</span>, mu<span class="op">=</span>mu, sigma<span class="op">=</span>sigma, observed<span class="op">=</span>outcome)</span>
<span id="cb31-64"><a href="#cb31-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-65"><a href="#cb31-65" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Sampling</span></span>
<span id="cb31-66"><a href="#cb31-66" aria-hidden="true" tabindex="-1"></a>    trace <span class="op">=</span> pm.sample(<span class="dv">2000</span>, tune<span class="op">=</span><span class="dv">1000</span>, target_accept<span class="op">=</span><span class="fl">0.95</span>, return_inferencedata<span class="op">=</span><span class="va">True</span>, random_seed<span class="op">=</span><span class="dv">11088</span>)</span>
<span id="cb31-67"><a href="#cb31-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-68"><a href="#cb31-68" aria-hidden="true" tabindex="-1"></a>trace.posterior <span class="op">=</span> trace.posterior.rename({<span class="st">'Beta_dim_0'</span>: <span class="st">'variable'</span>})</span>
<span id="cb31-69"><a href="#cb31-69" aria-hidden="true" tabindex="-1"></a>trace.posterior[<span class="st">'variable'</span>] <span class="op">=</span> (<span class="st">'variable'</span>, predictor_names)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-3-posterior-summary" class="level4">
<h4 class="anchored" data-anchor-id="step-3-posterior-summary">📊 Step 3: Posterior Summary</h4>
<p>After sampling from the posterior distribution using PyMC, we now have a large collection of samples (called the trace) representing the joint posterior distribution of the model parameters.</p>
<p>The posterior summary allows us to understand:</p>
<ul>
<li><strong>Central tendency</strong> (e.g., mean or median of each parameter estimate)</li>
<li><strong>Uncertainty</strong> (e.g., standard deviation or credible intervals)</li>
<li><strong>Effect direction and strength</strong> (is the coefficient consistently above/below zero?)</li>
</ul>
<p>Here’s how to examine this in Python using arviz:</p>
<div id="79c4afaf" class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>az.summary(trace, var_names<span class="op">=</span>[<span class="st">"Intercept"</span>, <span class="st">"Beta"</span>, <span class="st">"Sigma"</span>], hdi_prob<span class="op">=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><strong>Mean</strong>: Posterior mean (expected value)</li>
<li><strong>SD</strong>: Posterior standard deviation</li>
<li><strong>HDI (Highest Density Interval)</strong>: The most credible interval containing 95% of the posterior probability mass. If this interval excludes 0, the effect is considered statistically credible (akin to ‘significant’).</li>
</ul>
<p>🧭 How to interpret: - If the <strong>HDI excludes zero</strong>, it suggests a consistent effect (e.g., a real impact of the treatment). - If the <strong>HDI includes zero</strong>, there’s high uncertainty about whether that variable truly affects the outcome.</p>
<hr>
<p>📈 Plotting the posterior:</p>
<p>Visualising the posterior is an intuitive way to understand the model:</p>
<div id="55289fea" class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>az.plot_forest(trace, var_names<span class="op">=</span>[<span class="st">"Beta"</span>], combined<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="interpretation-3" class="level1">
<h1>Interpretation</h1>
<p>The key output here is the coefficient for <code>Group_Hipponol</code>. If its 95% Highest Posterior Density Interval (HDI) does not overlap with zero, there’s strong evidence that <code>Hipponol</code> affects SBP change compared to control.</p>
</section>
<section id="comparing-treatment-effects-on-sbp-change" class="level1">
<h1>🧪 Comparing Treatment Effects on SBP Change</h1>
<p>We evaluated the effect of the Hipponol intervention on the change in <strong>systolic blood pressure (SBP)</strong> using three different analytical approaches: a standard independent samples <strong>T-test</strong>, a classical <strong>Ordinary Least Squares (OLS) regression</strong>, and a <strong>Bayesian regression model</strong>. Each method provides an estimate of the mean difference in SBP change between the treatment (Hipponol) and control groups, along with a measure of uncertainty.</p>
<section id="t-test" class="level2">
<h2 class="anchored" data-anchor-id="t-test">🔹 T-test</h2>
<p>The T-test compares the mean SBP change directly between the two groups, assuming equal variance. The estimated mean difference was statistically significant, indicating that the SBP change in the Hipponol group was different from the control group. This method provides a straightforward test of the null hypothesis with a confidence interval for the mean difference.</p>
<ul>
<li><strong>Advantage</strong>: Simple and easy to interpret.</li>
<li><strong>Limitation</strong>: Does not adjust for potential confounders such as age, sex, or smoking status.</li>
</ul>
</section>
<section id="ancova" class="level2">
<h2 class="anchored" data-anchor-id="ancova">🔹 ANCOVA</h2>
<p>The Analysis of Covariance (ANCOVA) extends the OLS model by including baseline covariates—such as age, sex, and smoking status—to control for confounding and improve precision. This method adjusts the treatment effect for baseline imbalances and provides a more accurate estimate.</p>
<ul>
<li><strong>Advantage</strong>: Adjusts for potential confounders, improving estimate precision.</li>
<li><strong>Limitation</strong>: Requires linear relationships between covariates and outcome, and assumes homogeneity of regression slopes.</li>
</ul>
</section>
<section id="ols-regression" class="level2">
<h2 class="anchored" data-anchor-id="ols-regression">🔹 OLS Regression</h2>
<p>The OLS regression treated group membership as a binary predictor for SBP change. The estimate from this model was numerically identical to the T-test result because no additional covariates were included. However, regression frameworks allow for the extension to multiple covariates and interaction terms.</p>
<ul>
<li><strong>Advantage</strong>: Can be extended to include confounders or interactions.</li>
<li><strong>Limitation</strong>: Assumes linear relationships and homoscedasticity.</li>
</ul>
</section>
<section id="bayesian-regression" class="level2">
<h2 class="anchored" data-anchor-id="bayesian-regression">🔹 Bayesian Regression</h2>
<p>The Bayesian model estimated the treatment effect using probabilistic priors and provided a full posterior distribution for the treatment coefficient. The 95% Highest Density Interval (HDI) offers a Bayesian analogue to the confidence interval, interpreted as the range within which the true effect lies with 95% probability.</p>
<ul>
<li><strong>Advantage</strong>: Flexibility, intuitive probabilistic interpretation, and explicit incorporation of prior beliefs.</li>
<li><strong>Limitation</strong>: Requires computational resources and careful choice of priors.</li>
</ul>
<div id="b514799b" class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Assume df is already loaded and processed</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'SBP_Change'</span>] <span class="op">=</span> df[<span class="st">'Followup_SBP'</span>] <span class="op">-</span> df[<span class="st">'Baseline_SBP'</span>]</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Treatment'</span>] <span class="op">=</span> (df[<span class="st">'Group'</span>] <span class="op">==</span> <span class="st">'Hipponol'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="co"># --- T-test ---</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>control <span class="op">=</span> df[df[<span class="st">'Treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'SBP_Change'</span>]</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>hipponol <span class="op">=</span> df[df[<span class="st">'Treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'SBP_Change'</span>]</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>t_stat, t_pval <span class="op">=</span> stats.ttest_ind(hipponol, control)</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>mean_diff <span class="op">=</span> hipponol.mean() <span class="op">-</span> control.mean()</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>ci_low, ci_high <span class="op">=</span> stats.t.interval(</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.95</span>, df<span class="op">=</span><span class="bu">len</span>(control) <span class="op">+</span> <span class="bu">len</span>(hipponol) <span class="op">-</span> <span class="dv">2</span>,</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    loc<span class="op">=</span>mean_diff,</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>    scale<span class="op">=</span>stats.sem(np.concatenate([hipponol.values, <span class="op">-</span>control.values]))</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a><span class="co"># --- OLS Regression ---</span></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>model_adj <span class="op">=</span> smf.ols(<span class="st">'SBP_Change ~ Treatment + Age + C(Sex) + C(SmokingStatus)'</span>, data<span class="op">=</span>df).fit()</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>ols_estimate <span class="op">=</span> model_adj.params[<span class="st">'Treatment'</span>]</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>ols_ci_low, ols_ci_high <span class="op">=</span> model_adj.conf_int().loc[<span class="st">'Treatment'</span>]</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a><span class="co"># ANCOVA: Adjusting for age, sex, smoking</span></span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a>df_ancova <span class="op">=</span> df.copy()</span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a>df_ancova <span class="op">=</span> pd.get_dummies(df_ancova, columns<span class="op">=</span>[<span class="st">'Sex'</span>, <span class="st">'SmokingStatus'</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>formula <span class="op">=</span> <span class="st">"SBP_Change ~ Treatment + Age + Sex_Male + SmokingStatus_Smoker"</span></span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a>y_ancova, X_ancova <span class="op">=</span> patsy.dmatrices(formula, data<span class="op">=</span>df_ancova, return_type<span class="op">=</span><span class="st">'dataframe'</span>)</span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a>ancova_model <span class="op">=</span> sm.OLS(y_ancova, X_ancova).fit()</span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a>ancova_estimate <span class="op">=</span> ancova_model.params[<span class="st">'Treatment'</span>]</span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a>ancova_ci_low, ancova_ci_high <span class="op">=</span> ancova_model.conf_int().loc[<span class="st">'Treatment'</span>]</span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Bayesian Regression ---</span></span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> pm.Model() <span class="im">as</span> model:</span>
<span id="cb34-36"><a href="#cb34-36" aria-hidden="true" tabindex="-1"></a>    beta_0 <span class="op">=</span> pm.Normal(<span class="st">"Intercept"</span>, mu<span class="op">=</span><span class="dv">0</span>, sigma<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb34-37"><a href="#cb34-37" aria-hidden="true" tabindex="-1"></a>    beta_1 <span class="op">=</span> pm.Normal(<span class="st">"Treatment"</span>, mu<span class="op">=</span><span class="dv">0</span>, sigma<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb34-38"><a href="#cb34-38" aria-hidden="true" tabindex="-1"></a>    sigma <span class="op">=</span> pm.HalfNormal(<span class="st">"Sigma"</span>, sigma<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb34-39"><a href="#cb34-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-40"><a href="#cb34-40" aria-hidden="true" tabindex="-1"></a>    mu <span class="op">=</span> beta_0 <span class="op">+</span> beta_1 <span class="op">*</span> df[<span class="st">'Treatment'</span>].values</span>
<span id="cb34-41"><a href="#cb34-41" aria-hidden="true" tabindex="-1"></a>    y_obs <span class="op">=</span> pm.Normal(<span class="st">"y_obs"</span>, mu<span class="op">=</span>mu, sigma<span class="op">=</span>sigma, observed<span class="op">=</span>df[<span class="st">'SBP_Change'</span>])</span>
<span id="cb34-42"><a href="#cb34-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-43"><a href="#cb34-43" aria-hidden="true" tabindex="-1"></a>    trace <span class="op">=</span> pm.sample(<span class="dv">2000</span>, tune<span class="op">=</span><span class="dv">1000</span>, target_accept<span class="op">=</span><span class="fl">0.95</span>, return_inferencedata<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb34-44"><a href="#cb34-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-45"><a href="#cb34-45" aria-hidden="true" tabindex="-1"></a>bayes_summary <span class="op">=</span> az.summary(trace, var_names<span class="op">=</span>[<span class="st">"Treatment"</span>], hdi_prob<span class="op">=</span><span class="fl">0.95</span>)</span>
<span id="cb34-46"><a href="#cb34-46" aria-hidden="true" tabindex="-1"></a>bayes_estimate <span class="op">=</span> bayes_summary.loc[<span class="st">"Treatment"</span>, <span class="st">"mean"</span>]</span>
<span id="cb34-47"><a href="#cb34-47" aria-hidden="true" tabindex="-1"></a>bayes_hdi_low <span class="op">=</span> bayes_summary.loc[<span class="st">"Treatment"</span>, <span class="st">"hdi_2.5%"</span>]</span>
<span id="cb34-48"><a href="#cb34-48" aria-hidden="true" tabindex="-1"></a>bayes_hdi_high <span class="op">=</span> bayes_summary.loc[<span class="st">"Treatment"</span>, <span class="st">"hdi_97.5%"</span>]</span>
<span id="cb34-49"><a href="#cb34-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-50"><a href="#cb34-50" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Comparison Table with Formatting ---</span></span>
<span id="cb34-51"><a href="#cb34-51" aria-hidden="true" tabindex="-1"></a>effect_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb34-52"><a href="#cb34-52" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Method"</span>: [<span class="st">"T-test"</span>, <span class="st">"OLS regression"</span>, <span class="st">"ANCOVA"</span>, <span class="st">"Bayesian regression"</span>],</span>
<span id="cb34-53"><a href="#cb34-53" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Estimate (mmHg)"</span>: [mean_diff, ols_estimate, ancova_estimate, bayes_estimate],</span>
<span id="cb34-54"><a href="#cb34-54" aria-hidden="true" tabindex="-1"></a>    <span class="st">"95% CI Lower"</span>: [ci_low, ols_ci_low, ancova_ci_low, bayes_hdi_low],</span>
<span id="cb34-55"><a href="#cb34-55" aria-hidden="true" tabindex="-1"></a>    <span class="st">"95% CI Upper"</span>: [ci_high, ols_ci_high, ancova_ci_high, bayes_hdi_high]</span>
<span id="cb34-56"><a href="#cb34-56" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb34-57"><a href="#cb34-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-58"><a href="#cb34-58" aria-hidden="true" tabindex="-1"></a><span class="co"># Round values for presentation</span></span>
<span id="cb34-59"><a href="#cb34-59" aria-hidden="true" tabindex="-1"></a>effect_df <span class="op">=</span> effect_df.<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb34-60"><a href="#cb34-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-61"><a href="#cb34-61" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(effect_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="relationship-between-ancova-and-ols-regression" class="level3">
<h3 class="anchored" data-anchor-id="relationship-between-ancova-and-ols-regression">🔄 Relationship Between ANCOVA and OLS Regression</h3>
<p>In this instance, <strong>Analysis of Covariance (ANCOVA)</strong> and <strong>Ordinary Least Squares (OLS) regression</strong> provide <strong>identical results</strong>—but why is that the case?</p>
<section id="conceptual-overlap" class="level4">
<h4 class="anchored" data-anchor-id="conceptual-overlap">🧠 Conceptual Overlap</h4>
<p>ANCOVA is essentially a special case of linear regression. Specifically, it combines:</p>
<ul>
<li><strong>ANOVA</strong>: for testing differences between categorical groups (e.g.&nbsp;treatment vs.&nbsp;control), and<br>
</li>
<li><strong>Regression</strong>: for adjusting these comparisons based on continuous or additional categorical covariates (e.g.&nbsp;age, sex, smoking status).</li>
</ul>
<p>Thus, ANCOVA is not a fundamentally different statistical method but rather a <strong>framework for interpreting a linear model</strong> that includes both categorical and continuous predictors. When implemented in software such as Python’s <code>statsmodels</code>, ANCOVA is conducted via the <strong>same OLS regression engine</strong> as any standard linear regression model.</p>
</section>
<section id="technical-equivalence" class="level4">
<h4 class="anchored" data-anchor-id="technical-equivalence">📊 Technical Equivalence</h4>
<p>The following model, framed as an OLS regression:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">'SBP_Change ~ Treatment + Age + C(Sex) + C(SmokingStatus)'</span>, data<span class="op">=</span>df).fit()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>is analytically identical to an ANCOVA testing the <strong>effect of Treatment on SBP change</strong>, <strong>adjusting for Age, Sex, and Smoking Status</strong>. The categorical variables are automatically dummy-coded, and the model estimates group differences while controlling for the covariates.</p>
<p>Both approaches: - Estimate coefficients using least squares - Provide p-values, confidence intervals, and model diagnostics - Are suitable for continuous outcomes (like SBP change)</p>
</section>
<section id="summary" class="level4">
<h4 class="anchored" data-anchor-id="summary">🧾 Summary</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 52%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>What it Emphasises</th>
<th>Underlying Method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>ANCOVA</strong></td>
<td>Group comparison <strong>with adjustment</strong></td>
<td>Linear regression</td>
</tr>
<tr class="even">
<td><strong>OLS Regression</strong></td>
<td>Flexible modelling of continuous outcomes</td>
<td>Linear regression</td>
</tr>
</tbody>
</table>
<p><strong>✅ Conclusion:</strong><br>
Whether you call it ANCOVA or OLS regression, you’re using the <strong>same statistical engine</strong>. The terminology difference mostly reflects <strong>intent and interpretation</strong>, not implementation.</p>
</section>
</section>
</section>
</section>
<section id="summary-of-key-findings" class="level1">
<h1>📜 Summary of Key Findings</h1>
<section id="primary-outcome-survival" class="level2">
<h2 class="anchored" data-anchor-id="primary-outcome-survival">🧬 Primary Outcome: Survival</h2>
<ul>
<li><strong>Chi-squared test</strong>: Suggested a difference in survival between groups.</li>
<li><strong>Logistic regression</strong>:
<ul>
<li>Hipponol group had <strong>higher odds of survival</strong> than the control group.</li>
<li>Adjusted models controlling for age, sex, and smoking status confirmed this effect.</li>
</ul></li>
<li><strong>Bayesian logistic regression</strong>:
<ul>
<li>The posterior distribution for the group effect was mostly above 0.</li>
<li>The <strong>95% credible interval</strong> for the odds ratio <strong>excluded 1</strong>, supporting a positive treatment effect.</li>
<li>Interpretation: <strong>There is a high probability that Hipponol improves survival</strong>.</li>
</ul></li>
<li><strong>Kaplan–Meier analysis</strong>:
<ul>
<li>Survival curves diverged, favouring Hipponol.</li>
<li><strong>Log-rank test</strong> confirmed a statistically significant difference.</li>
</ul></li>
<li><strong>Cox proportional hazards model</strong>:</li>
<li>Adjusted hazard ratio showed reduced risk in the Hipponol group.</li>
<li>Proportional hazards assumption was checked and met.</li>
</ul>
</section>
<section id="secondary-outcome-systolic-blood-pressure-sbp" class="level2">
<h2 class="anchored" data-anchor-id="secondary-outcome-systolic-blood-pressure-sbp">💉 Secondary Outcome: Systolic Blood Pressure (SBP)</h2>
<ul>
<li><strong>Visual exploration</strong>: KDE plots showed a shift toward greater SBP reduction in the Hipponol group.</li>
<li><strong>T-test</strong>: A statistically significant <strong>greater reduction</strong> in SBP in the Hipponol group.</li>
<li><strong>OLS regression</strong>: Consistent estimate with T-test; easy to extend to more predictors.</li>
<li><strong>ANCOVA</strong>: Adjusting for baseline SBP, age, sex, and smoking confirmed the treatment effect.</li>
<li><strong>Bayesian regression</strong>:
<ul>
<li>Estimated posterior distribution of the treatment effect.</li>
<li>95% HDI for the treatment coefficient excluded 0, confirming a likely SBP-lowering effect.</li>
</ul></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>